# Generated by Django 6.0.3 on 2026-06-21 03:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AwarenessCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('topic', models.CharField(choices=[('manajemen_risiko', 'Manajemen Risiko'), ('kpmr', 'KPMR'), ('risiko_korporat', 'Risiko Korporat'), ('risiko_operasional', 'Risiko Operasional'), ('risiko_proyek', 'Risiko Proyek'), ('kepatuhan', 'Kepatuhan'), ('cyber_risk', 'Cyber Risk'), ('business_continuity', 'Business Continuity')], default='manajemen_risiko', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('passing_score', models.PositiveSmallIntegerField(default=70)),
                ('max_attempts', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('time_limit_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_awareness_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_date', 'title'),
                'permissions': (('view_campaign_report', 'Can view awareness campaign report'), ('export_campaign_result', 'Can export awareness campaign result')),
            },
        ),
        migrations.CreateModel(
            name='AwarenessAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'Sedang dikerjakan'), ('submitted', 'Submitted'), ('passed', 'Lulus'), ('failed', 'Tidak lulus'), ('expired', 'Expired')], default='in_progress', max_length=20)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awareness_attempts', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='awareness.awarenesscampaign')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='AwarenessQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('mudah', 'Mudah'), ('sedang', 'Sedang'), ('sulit', 'Sulit')], default='mudah', max_length=20)),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='awareness.awarenesscampaign')),
            ],
            options={
                'ordering': ('campaign', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AwarenessAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='awareness.awarenessattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='awareness.awarenessquestion')),
            ],
            options={
                'ordering': ('question__order', 'question_id'),
            },
        ),
        migrations.AddIndex(
            model_name='awarenessattempt',
            index=models.Index(fields=['campaign', 'user', 'status'], name='awareness_a_campaig_e58273_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='awarenessanswer',
            unique_together={('attempt', 'question')},
        ),
    ]
