# Generated by Django 6.0.3 on 2026-06-21 05:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='awarenessattempt',
            constraint=models.UniqueConstraint(fields=('campaign', 'user', 'attempt_number'), name='awareness_unique_attempt_number'),
        ),
    ]
