# Generated by Django 6.0.3 on 2026-06-22 02:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0002_awarenessattempt_awareness_unique_attempt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='awarenesscampaign',
            name='material_image',
            field=models.FileField(blank=True, help_text='Upload gambar materi awareness yang dibaca user sebelum mulai kuis.', upload_to='awareness/materials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
