# Generated by Django 6.0.3 on 2026-07-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0003_awarenesscampaign_material_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='awarenesscampaign',
            name='email_header_subtitle',
            field=models.CharField(blank=True, default='', help_text='Contoh: Manajemen Risiko. Jika kosong, sistem memakai topik campaign.', max_length=160, verbose_name='Subjudul Header Email'),
        ),
        migrations.AddField(
            model_name='awarenesscampaign',
            name='email_header_title',
            field=models.CharField(blank=True, default='', help_text='Contoh: Awareness Manajemen Risiko. Jika kosong, sistem memakai judul campaign.', max_length=160, verbose_name='Judul Header Email'),
        ),
        migrations.AddField(
            model_name='awarenesscampaign',
            name='notification_test_email',
            field=models.EmailField(blank=True, default='', help_text='Tujuan default tombol Kirim Test. Jika kosong, sistem memakai email admin yang login.', max_length=254, verbose_name='Email Test Notifikasi'),
        ),
    ]
