# Generated by Django 6.0.3 on 2026-07-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0004_awarenesscampaign_email_header_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awarenesscampaign',
            name='notification_test_email',
            field=models.EmailField(blank=True, default='', help_text='Tujuan default tombol Kirim Report. Jika kosong, sistem memakai email admin yang login.', max_length=254, verbose_name='Email Tujuan Report'),
        ),
    ]
