# Generated by Django 6.0.3 on 2026-07-13 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0005_alter_awarenesscampaign_notification_test_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwarenessUnitTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(help_text='Nama bidang/unit sesuai data jumlah pegawai.', max_length=180, verbose_name='Bidang / Unit')),
                ('employee_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Pegawai')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Urutan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_targets', to='awareness.awarenesscampaign', verbose_name='Campaign')),
            ],
            options={
                'verbose_name': 'Target Pegawai Awareness per Unit',
                'verbose_name_plural': 'Target Pegawai Awareness per Unit',
                'ordering': ('campaign', 'order', 'unit_name'),
                'constraints': [models.UniqueConstraint(fields=('campaign', 'unit_name'), name='awareness_unique_unit_target')],
            },
        ),
    ]
