# Generated by Django 6.0.3 on 2026-03-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_id', models.CharField(max_length=20)),
                ('risk_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('likelihood', models.IntegerField()),
                ('impact', models.IntegerField()),
                ('mitigation_plan', models.TextField()),
            ],
        ),
    ]
