# Generated by Django 6.0.3 on 2026-03-13 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Final', 'Final')], default='Draft', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='management_contracts', to='auth.group')),
            ],
            options={
                'verbose_name': 'Kontrak Manajemen',
                'verbose_name_plural': 'Kontrak Manajemen',
                'ordering': ['-year', 'business_unit__name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ManagementContractIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.PositiveIntegerField()),
                ('section_code', models.CharField(blank=True, max_length=5, null=True)),
                ('section_name', models.CharField(blank=True, max_length=255, null=True)),
                ('indicator_name', models.TextField(verbose_name='Indikator Kinerja Kunci')),
                ('formula', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('target_value', models.CharField(blank=True, max_length=100, null=True)),
                ('direction', models.CharField(choices=[('UP', 'Naik'), ('DOWN', 'Turun'), ('NONE', 'Tidak Ada')], default='NONE', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='risk.managementcontract')),
            ],
            options={
                'verbose_name': 'Detail Kontrak Manajemen',
                'verbose_name_plural': 'Detail Kontrak Manajemen',
                'ordering': ['contract', 'row_no'],
            },
        ),
    ]
