# Generated by Django 6.0.3 on 2026-03-30 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('risk', '0002_managementcontract_managementcontractindicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskregister',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='riskregister',
            name='risk_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskregister',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('On Progress', 'On Progress'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='managementcontract',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='management_contracts', to='auth.group', verbose_name='Bidang / Unit Bisnis'),
        ),
        migrations.AlterField(
            model_name='managementcontract',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Keterangan'),
        ),
        migrations.AlterField(
            model_name='managementcontract',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Judul Kontrak'),
        ),
        migrations.AlterField(
            model_name='managementcontract',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='riskregister',
            name='mitigation_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskregister',
            name='risk_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='ManagementContractSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(help_text='Contoh: A, B, C, D, E, F', max_length=5, verbose_name='Kode Bagian')),
                ('section_name', models.CharField(max_length=255, verbose_name='Nama Bagian / Perspektif')),
                ('section_weight', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Bobot Bagian')),
                ('order_no', models.PositiveIntegerField(default=1, verbose_name='Urutan')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='risk.managementcontract', verbose_name='Kontrak Manajemen')),
            ],
            options={
                'verbose_name': 'Bagian Kontrak Manajemen',
                'verbose_name_plural': 'Bagian Kontrak Manajemen',
                'ordering': ['contract', 'order_no', 'section_code'],
                'unique_together': {('contract', 'section_code')},
            },
        ),
        migrations.CreateModel(
            name='ManagementContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.PositiveIntegerField(verbose_name='No')),
                ('indicator_name', models.TextField(verbose_name='Indikator Kinerja Kunci')),
                ('formula', models.TextField(blank=True, null=True, verbose_name='Formula')),
                ('unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Satuan')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Bobot')),
                ('target_value', models.CharField(blank=True, max_length=100, null=True, verbose_name='Target')),
                ('direction', models.CharField(choices=[('UP', 'Naik'), ('DOWN', 'Turun'), ('NONE', 'Tidak Ada')], default='NONE', max_length=10, verbose_name='Arah')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='risk.managementcontractsection', verbose_name='Bagian Kontrak Manajemen')),
            ],
            options={
                'verbose_name': 'Item Kontrak Manajemen',
                'verbose_name_plural': 'Item Kontrak Manajemen',
                'ordering': ['section', 'row_no'],
                'unique_together': {('section', 'row_no')},
            },
        ),
        migrations.DeleteModel(
            name='ManagementContractIndicator',
        ),
    ]
