# Generated by Django 6.0.3 on 2026-03-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('risk', '0003_riskregister_owner_riskregister_risk_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managementcontractsection',
            options={'ordering': ['contract', 'section_code'], 'verbose_name': 'Bagian Kontrak Manajemen', 'verbose_name_plural': 'Bagian Kontrak Manajemen'},
        ),
        migrations.AlterModelOptions(
            name='riskregister',
            options={'ordering': ['risk_id'], 'verbose_name': 'Risk Register', 'verbose_name_plural': 'Risk Register'},
        ),
        migrations.AlterUniqueTogether(
            name='managementcontractitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='managementcontractsection',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='managementcontract',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Final', 'Final')], default='Draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='riskregister',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='riskregister',
            name='impact',
            field=models.IntegerField(verbose_name='Impact'),
        ),
        migrations.AlterField(
            model_name='riskregister',
            name='likelihood',
            field=models.IntegerField(verbose_name='Likelihood'),
        ),
        migrations.AlterField(
            model_name='riskregister',
            name='mitigation_plan',
            field=models.TextField(blank=True, null=True, verbose_name='Rencana Mitigasi'),
        ),
        migrations.AlterField(
            model_name='riskregister',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='riskregister',
            name='risk_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='ID Risiko'),
        ),
        migrations.AlterField(
            model_name='riskregister',
            name='risk_name',
            field=models.CharField(max_length=200, verbose_name='Nama Risiko'),
        ),
        migrations.AlterField(
            model_name='riskregister',
            name='risk_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Risk Score'),
        ),
        migrations.AlterField(
            model_name='riskregister',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('On Progress', 'On Progress'), ('Closed', 'Closed')], default='Open', max_length=20, verbose_name='Status'),
        ),
        migrations.AddConstraint(
            model_name='managementcontract',
            constraint=models.UniqueConstraint(fields=('title', 'year', 'business_unit'), name='unique_management_contract_per_unit_year_title'),
        ),
        migrations.AddConstraint(
            model_name='managementcontractitem',
            constraint=models.UniqueConstraint(fields=('section', 'row_no'), name='unique_row_no_per_section'),
        ),
        migrations.AddConstraint(
            model_name='managementcontractsection',
            constraint=models.UniqueConstraint(fields=('contract', 'section_code'), name='unique_section_code_per_contract'),
        ),
        migrations.RemoveField(
            model_name='managementcontractsection',
            name='order_no',
        ),
        migrations.RemoveField(
            model_name='managementcontractsection',
            name='section_weight',
        ),
    ]
