# Generated by Django 6.0.3 on 2026-03-31 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('risk', '0004_alter_managementcontractsection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.PositiveIntegerField()),
                ('sasaran_bumn', models.CharField(blank=True, max_length=255, null=True)),
                ('sasaran_kbumn', models.CharField(blank=True, max_length=255, null=True)),
                ('taxonomy_t3', models.CharField(blank=True, max_length=255, null=True)),
                ('risk_category', models.CharField(blank=True, max_length=255, null=True)),
                ('risk_no', models.PositiveIntegerField()),
                ('risk_event', models.TextField()),
                ('risk_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['summary', 'item_no'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessmentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('company_name', models.CharField(default='PT Perusahaan Listrik Negara (Persero)', max_length=200)),
                ('ap_sh', models.CharField(default='PLN BATAM', max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved')], default='Draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', 'business_unit__name', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='managementcontract',
            options={'ordering': ['-year', 'business_unit__name', 'title']},
        ),
        migrations.AlterModelOptions(
            name='managementcontractitem',
            options={'ordering': ['section', 'row_no']},
        ),
        migrations.AlterModelOptions(
            name='managementcontractsection',
            options={'ordering': ['contract', 'section_code']},
        ),
        migrations.AlterModelOptions(
            name='riskregister',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='managementcontract',
            name='unique_management_contract_per_unit_year_title',
        ),
        migrations.RemoveConstraint(
            model_name='managementcontractitem',
            name='unique_row_no_per_section',
        ),
        migrations.RemoveConstraint(
            model_name='managementcontractsection',
            name='unique_section_code_per_contract',
        ),
        migrations.AlterField(
            model_name='managementcontract',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='management_contracts', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='managementcontract',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='managementcontract',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Final', 'Final')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='managementcontract',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='managementcontract',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='managementcontractitem',
            name='direction',
            field=models.CharField(choices=[('UP', 'Naik'), ('DOWN', 'Turun'), ('NONE', 'Tidak Ada')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='managementcontractitem',
            name='formula',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='managementcontractitem',
            name='indicator_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='managementcontractitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='managementcontractitem',
            name='row_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='managementcontractitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='risk.managementcontractsection'),
        ),
        migrations.AlterField(
            model_name='managementcontractitem',
            name='target_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='managementcontractitem',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='managementcontractitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='managementcontractsection',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='risk.managementcontract'),
        ),
        migrations.AlterField(
            model_name='managementcontractsection',
            name='section_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='managementcontractsection',
            name='section_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='riskregister',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='riskregister',
            name='impact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='riskregister',
            name='likelihood',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='riskregister',
            name='mitigation_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskregister',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='riskregister',
            name='risk_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='riskregister',
            name='risk_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='riskregister',
            name='risk_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskregister',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('On Progress', 'On Progress'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='managementcontract',
            constraint=models.UniqueConstraint(fields=('title', 'year', 'business_unit'), name='unique_contract_per_unit_year'),
        ),
        migrations.AddConstraint(
            model_name='managementcontractitem',
            constraint=models.UniqueConstraint(fields=('section', 'row_no'), name='unique_item_per_section'),
        ),
        migrations.AddConstraint(
            model_name='managementcontractsection',
            constraint=models.UniqueConstraint(fields=('contract', 'section_code'), name='unique_section_per_contract'),
        ),
        migrations.AddField(
            model_name='riskassessmentitem',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_items', to='auth.group'),
        ),
        migrations.AddField(
            model_name='riskassessmentitem',
            name='km_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_items', to='risk.managementcontractitem'),
        ),
        migrations.AddField(
            model_name='riskassessmentsummary',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_summaries', to='auth.group'),
        ),
        migrations.AddField(
            model_name='riskassessmentsummary',
            name='management_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_summaries', to='risk.managementcontract'),
        ),
        migrations.AddField(
            model_name='riskassessmentitem',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='risk.riskassessmentsummary'),
        ),
        migrations.AddConstraint(
            model_name='riskassessmentitem',
            constraint=models.UniqueConstraint(fields=('summary', 'item_no'), name='unique_item_per_summary'),
        ),
        migrations.AddConstraint(
            model_name='riskassessmentitem',
            constraint=models.UniqueConstraint(fields=('summary', 'risk_no'), name='unique_risk_per_summary'),
        ),
    ]
