# Generated by Django 6.0.3 on 2026-03-31 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0005_riskassessmentitem_riskassessmentsummary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyT3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kode')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Taxonomy T3')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Taxonomy T3',
                'verbose_name_plural': 'Taxonomy T3',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='riskassessmentitem',
            name='taxonomy_t3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_items', to='risk.taxonomyt3', verbose_name='Taxonomy T3'),
        ),
    ]
