# Generated by Django 6.0.3 on 2026-03-31 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('risk', '0006_taxonomyt3_alter_riskassessmentitem_taxonomy_t3'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagianKontrakManajemen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_bagian', models.CharField(max_length=5)),
                ('nama_bagian', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Transaksi Bagian Kontrak',
                'verbose_name_plural': 'Transaksi Bagian Kontrak',
                'ordering': ['kode_bagian'],
            },
        ),
        migrations.CreateModel(
            name='ItemKontrakManajemen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_urut', models.PositiveIntegerField()),
                ('indikator_kinerja_kunci', models.TextField()),
                ('bobot', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
            options={
                'verbose_name': 'Transaksi Item Kontrak',
                'verbose_name_plural': 'Transaksi Item Kontrak',
                'ordering': ['no_urut'],
            },
        ),
        migrations.CreateModel(
            name='KategoriRisiko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Master Kategori Risiko',
                'verbose_name_plural': 'Master Kategori Risiko',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='KontrakManajemen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('tahun', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Final', 'Final')], default='Draft', max_length=20)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transaksi Kontrak Manajemen',
                'verbose_name_plural': 'Transaksi Kontrak Manajemen',
                'ordering': ['-tahun'],
            },
        ),
        migrations.CreateModel(
            name='KPMRItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_item', models.PositiveIntegerField()),
                ('perlakuan_risiko', models.TextField(blank=True, null=True)),
                ('bukti', models.TextField(blank=True, null=True)),
                ('nilai_kpmr', models.IntegerField(blank=True, null=True)),
                ('status_kpmr', models.CharField(choices=[('Sesuai', 'Sesuai'), ('Tidak Sesuai', 'Tidak Sesuai'), ('Perlu Perbaikan', 'Perlu Perbaikan')], default='Perlu Perbaikan', max_length=50)),
                ('catatan', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Transaksi KPMR Item',
                'verbose_name_plural': 'Transaksi KPMR Item',
            },
        ),
        migrations.CreateModel(
            name='KPMRSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('tahun', models.PositiveIntegerField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transaksi KPMR Summary',
                'verbose_name_plural': 'Transaksi KPMR Summary',
            },
        ),
        migrations.CreateModel(
            name='ReAssessmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_item', models.PositiveIntegerField()),
                ('no_risiko', models.PositiveIntegerField()),
                ('peristiwa_risiko', models.TextField()),
                ('deskripsi_peristiwa_risiko', models.TextField()),
            ],
            options={
                'verbose_name': 'Transaksi Re-Assessment Item',
                'verbose_name_plural': 'Transaksi Re-Assessment Item',
            },
        ),
        migrations.CreateModel(
            name='ReAssessmentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('tahun', models.PositiveIntegerField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transaksi Re-Assessment Summary',
                'verbose_name_plural': 'Transaksi Re-Assessment Summary',
            },
        ),
        migrations.CreateModel(
            name='SasaranKBUMN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Master Sasaran KBUMN',
                'verbose_name_plural': 'Master Sasaran KBUMN',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='TaksonomiT3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Master Taksonomi T3',
                'verbose_name_plural': 'Master Taksonomi T3',
                'ordering': ['kode'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='managementcontract',
            name='unique_contract_per_unit_year',
        ),
        migrations.RemoveField(
            model_name='riskassessmentsummary',
            name='management_contract',
        ),
        migrations.RemoveConstraint(
            model_name='managementcontractitem',
            name='unique_item_per_section',
        ),
        migrations.RemoveConstraint(
            model_name='managementcontractsection',
            name='unique_section_per_contract',
        ),
        migrations.RemoveConstraint(
            model_name='riskassessmentitem',
            name='unique_item_per_summary',
        ),
        migrations.RemoveConstraint(
            model_name='riskassessmentitem',
            name='unique_risk_per_summary',
        ),
        migrations.RemoveField(
            model_name='riskassessmentsummary',
            name='business_unit',
        ),
        migrations.DeleteModel(
            name='RiskRegister',
        ),
        migrations.AddField(
            model_name='itemkontrakmanajemen',
            name='bagian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='risk.bagiankontrakmanajemen'),
        ),
        migrations.AddField(
            model_name='kontrakmanajemen',
            name='unit_bisnis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
        migrations.AddField(
            model_name='bagiankontrakmanajemen',
            name='kontrak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bagian', to='risk.kontrakmanajemen'),
        ),
        migrations.AddField(
            model_name='kpmrsummary',
            name='unit_bisnis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
        migrations.AddField(
            model_name='kpmritem',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='risk.kpmrsummary'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='kategori_risiko',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.kategoririsiko'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='km_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='risk.itemkontrakmanajemen'),
        ),
        migrations.AddField(
            model_name='kpmritem',
            name='reassessment_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='risk.reassessmentitem'),
        ),
        migrations.AddField(
            model_name='reassessmentsummary',
            name='kontrak_manajemen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='risk.kontrakmanajemen'),
        ),
        migrations.AddField(
            model_name='reassessmentsummary',
            name='unit_bisnis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='risk.reassessmentsummary'),
        ),
        migrations.AddField(
            model_name='kpmrsummary',
            name='reassessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='risk.reassessmentsummary'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='sasaran_kbumn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.sasarankbumn'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='taksonomi_t3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.taksonomit3'),
        ),
        migrations.RemoveField(
            model_name='managementcontractitem',
            name='section',
        ),
        migrations.RemoveField(
            model_name='managementcontractsection',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='riskassessmentitem',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='riskassessmentitem',
            name='km_item',
        ),
        migrations.RemoveField(
            model_name='riskassessmentitem',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='riskassessmentitem',
            name='taxonomy_t3',
        ),
        migrations.DeleteModel(
            name='ManagementContract',
        ),
        migrations.DeleteModel(
            name='ManagementContractSection',
        ),
        migrations.DeleteModel(
            name='ManagementContractItem',
        ),
        migrations.DeleteModel(
            name='RiskAssessmentSummary',
        ),
        migrations.DeleteModel(
            name='RiskAssessmentItem',
        ),
        migrations.DeleteModel(
            name='TaxonomyT3',
        ),
    ]
