# Generated by Django 6.0.3 on 2026-04-01 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('risk', '0007_bagiankontrakmanajemen_itemkontrakmanajemen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilRisikoKorporatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_item', models.PositiveIntegerField(verbose_name='No Item')),
                ('sasaran_korporat', models.CharField(max_length=255, verbose_name='Sasaran Korporat')),
                ('peristiwa_risiko', models.TextField(verbose_name='Peristiwa Risiko Korporat')),
                ('dampak', models.IntegerField(blank=True, null=True, verbose_name='Dampak')),
                ('kemungkinan', models.IntegerField(blank=True, null=True, verbose_name='Kemungkinan')),
                ('level_risiko', models.IntegerField(blank=True, null=True, verbose_name='Level Risiko')),
                ('perlakuan_risiko', models.TextField(blank=True, null=True, verbose_name='Perlakuan Risiko')),
                ('pemilik_risiko', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pemilik Risiko')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Item Risiko Korporat',
                'verbose_name_plural': 'KORPORAT — Item Risiko',
                'ordering': ['summary', 'no_item'],
            },
        ),
        migrations.CreateModel(
            name='ProfilRisikoKorporatSumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
            ],
            options={
                'verbose_name': 'Sumber Risiko Korporat',
                'verbose_name_plural': 'KORPORAT — Sumber Risiko',
            },
        ),
        migrations.CreateModel(
            name='ProfilRisikoKorporatSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul Profil Risiko Korporat')),
                ('tahun', models.PositiveIntegerField(verbose_name='Tahun')),
                ('nama_perusahaan', models.CharField(default='PT PLN Batam', max_length=200, verbose_name='Nama Perusahaan')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Final', 'Final')], default='Draft', max_length=20, verbose_name='Status')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
            ],
            options={
                'verbose_name': 'Profil Risiko Korporat',
                'verbose_name_plural': 'KORPORAT — Profil Risiko',
                'ordering': ['-tahun', 'judul'],
            },
        ),
        migrations.AlterModelOptions(
            name='bagiankontrakmanajemen',
            options={'ordering': ['kontrak', 'kode_bagian'], 'verbose_name': 'Bagian Kontrak', 'verbose_name_plural': 'TRANSAKSI UNIT — Bagian Kontrak'},
        ),
        migrations.AlterModelOptions(
            name='itemkontrakmanajemen',
            options={'ordering': ['bagian', 'no_urut'], 'verbose_name': 'Item Kontrak', 'verbose_name_plural': 'TRANSAKSI UNIT — Item Kontrak'},
        ),
        migrations.AlterModelOptions(
            name='kategoririsiko',
            options={'ordering': ['kode'], 'verbose_name': 'Master Kategori Risiko', 'verbose_name_plural': 'MASTER — Kategori Risiko'},
        ),
        migrations.AlterModelOptions(
            name='kontrakmanajemen',
            options={'ordering': ['-tahun', 'judul'], 'verbose_name': 'Kontrak Manajemen Unit/Bidang', 'verbose_name_plural': 'TRANSAKSI UNIT — Kontrak Manajemen'},
        ),
        migrations.AlterModelOptions(
            name='kpmritem',
            options={'ordering': ['summary', 'no_item'], 'verbose_name': 'Item KPMR', 'verbose_name_plural': 'TRANSAKSI UNIT — Item KPMR'},
        ),
        migrations.AlterModelOptions(
            name='kpmrsummary',
            options={'ordering': ['-tahun', 'judul'], 'verbose_name': 'KPMR Unit/Bidang', 'verbose_name_plural': 'TRANSAKSI UNIT — KPMR'},
        ),
        migrations.AlterModelOptions(
            name='reassessmentitem',
            options={'ordering': ['summary', 'no_item'], 'verbose_name': 'Item Risiko Unit/Bidang', 'verbose_name_plural': 'TRANSAKSI UNIT — Item Re-Assessment'},
        ),
        migrations.AlterModelOptions(
            name='reassessmentsummary',
            options={'ordering': ['-tahun', 'judul'], 'verbose_name': 'Profil Risiko Unit/Bidang', 'verbose_name_plural': 'TRANSAKSI UNIT — Profil Risiko (Re-Assessment)'},
        ),
        migrations.AlterModelOptions(
            name='sasarankbumn',
            options={'ordering': ['kode'], 'verbose_name': 'Master Sasaran KBUMN', 'verbose_name_plural': 'MASTER — Sasaran KBUMN'},
        ),
        migrations.AlterModelOptions(
            name='taksonomit3',
            options={'ordering': ['kode'], 'verbose_name': 'Master Taksonomi T3', 'verbose_name_plural': 'MASTER — Taksonomi T3'},
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='unit_bisnis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='reassessment_item', to='auth.group', verbose_name='Bidang / Unit Bisnis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bagiankontrakmanajemen',
            name='kode_bagian',
            field=models.CharField(max_length=5, verbose_name='Kode Bagian'),
        ),
        migrations.AlterField(
            model_name='bagiankontrakmanajemen',
            name='kontrak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bagian', to='risk.kontrakmanajemen', verbose_name='Kontrak Manajemen'),
        ),
        migrations.AlterField(
            model_name='bagiankontrakmanajemen',
            name='nama_bagian',
            field=models.CharField(max_length=255, verbose_name='Nama Bagian'),
        ),
        migrations.AlterField(
            model_name='itemkontrakmanajemen',
            name='bagian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='risk.bagiankontrakmanajemen', verbose_name='Bagian Kontrak'),
        ),
        migrations.AlterField(
            model_name='itemkontrakmanajemen',
            name='bobot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Bobot'),
        ),
        migrations.AlterField(
            model_name='itemkontrakmanajemen',
            name='indikator_kinerja_kunci',
            field=models.TextField(verbose_name='Indikator Kinerja Kunci'),
        ),
        migrations.AlterField(
            model_name='itemkontrakmanajemen',
            name='no_urut',
            field=models.PositiveIntegerField(verbose_name='No Urut'),
        ),
        migrations.AlterField(
            model_name='kategoririsiko',
            name='aktif',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='kategoririsiko',
            name='deskripsi',
            field=models.TextField(blank=True, null=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='kategoririsiko',
            name='kode',
            field=models.CharField(max_length=50, unique=True, verbose_name='Kode'),
        ),
        migrations.AlterField(
            model_name='kategoririsiko',
            name='nama',
            field=models.CharField(max_length=255, verbose_name='Nama Kategori Risiko'),
        ),
        migrations.AlterField(
            model_name='kontrakmanajemen',
            name='dibuat_pada',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada'),
        ),
        migrations.AlterField(
            model_name='kontrakmanajemen',
            name='judul',
            field=models.CharField(max_length=200, verbose_name='Judul Kontrak'),
        ),
        migrations.AlterField(
            model_name='kontrakmanajemen',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Final', 'Final')], default='Draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='kontrakmanajemen',
            name='tahun',
            field=models.PositiveIntegerField(verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='kontrakmanajemen',
            name='unit_bisnis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kontrak_manajemen', to='auth.group', verbose_name='Bidang / Unit Bisnis'),
        ),
        migrations.AlterField(
            model_name='kpmritem',
            name='bukti',
            field=models.TextField(blank=True, null=True, verbose_name='Bukti'),
        ),
        migrations.AlterField(
            model_name='kpmritem',
            name='catatan',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan'),
        ),
        migrations.AlterField(
            model_name='kpmritem',
            name='nilai_kpmr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nilai KPMR'),
        ),
        migrations.AlterField(
            model_name='kpmritem',
            name='no_item',
            field=models.PositiveIntegerField(verbose_name='No Item'),
        ),
        migrations.AlterField(
            model_name='kpmritem',
            name='perlakuan_risiko',
            field=models.TextField(blank=True, null=True, verbose_name='Perlakuan Risiko'),
        ),
        migrations.AlterField(
            model_name='kpmritem',
            name='reassessment_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kpmr_item', to='risk.reassessmentitem', verbose_name='Re-Assessment Item'),
        ),
        migrations.AlterField(
            model_name='kpmritem',
            name='status_kpmr',
            field=models.CharField(choices=[('Sesuai', 'Sesuai'), ('Tidak Sesuai', 'Tidak Sesuai'), ('Perlu Perbaikan', 'Perlu Perbaikan')], default='Perlu Perbaikan', max_length=50, verbose_name='Status KPMR'),
        ),
        migrations.AlterField(
            model_name='kpmritem',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='risk.kpmrsummary', verbose_name='Summary KPMR'),
        ),
        migrations.AlterField(
            model_name='kpmrsummary',
            name='dibuat_pada',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada'),
        ),
        migrations.AlterField(
            model_name='kpmrsummary',
            name='judul',
            field=models.CharField(max_length=200, verbose_name='Judul KPMR'),
        ),
        migrations.AlterField(
            model_name='kpmrsummary',
            name='reassessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kpmr_summary', to='risk.reassessmentsummary', verbose_name='Re-Assessment'),
        ),
        migrations.AlterField(
            model_name='kpmrsummary',
            name='tahun',
            field=models.PositiveIntegerField(verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='kpmrsummary',
            name='unit_bisnis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kpmr_summary', to='auth.group', verbose_name='Bidang / Unit Bisnis'),
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='deskripsi_peristiwa_risiko',
            field=models.TextField(verbose_name='Deskripsi Peristiwa Risiko'),
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='kategori_risiko',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reassessment_item', to='risk.kategoririsiko', verbose_name='Kategori Risiko'),
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='km_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reassessment_item', to='risk.itemkontrakmanajemen', verbose_name='Sasaran PLN Batam (KM Unit/Bidang)'),
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='no_item',
            field=models.PositiveIntegerField(verbose_name='No Item'),
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='no_risiko',
            field=models.PositiveIntegerField(verbose_name='No Risiko'),
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='peristiwa_risiko',
            field=models.TextField(verbose_name='Peristiwa Risiko'),
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='sasaran_kbumn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reassessment_item', to='risk.sasarankbumn', verbose_name='Sasaran KBUMN'),
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='risk.reassessmentsummary', verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='taksonomi_t3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reassessment_item', to='risk.taksonomit3', verbose_name='Taksonomi Risiko PLN (T3)'),
        ),
        migrations.AlterField(
            model_name='reassessmentsummary',
            name='dibuat_pada',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada'),
        ),
        migrations.AlterField(
            model_name='reassessmentsummary',
            name='judul',
            field=models.CharField(max_length=200, verbose_name='Judul Re-Assessment'),
        ),
        migrations.AlterField(
            model_name='reassessmentsummary',
            name='kontrak_manajemen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reassessment_summary', to='risk.kontrakmanajemen', verbose_name='Kontrak Manajemen'),
        ),
        migrations.AlterField(
            model_name='reassessmentsummary',
            name='tahun',
            field=models.PositiveIntegerField(verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='reassessmentsummary',
            name='unit_bisnis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reassessment_summary', to='auth.group', verbose_name='Bidang / Unit Bisnis'),
        ),
        migrations.AlterField(
            model_name='sasarankbumn',
            name='aktif',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='sasarankbumn',
            name='deskripsi',
            field=models.TextField(blank=True, null=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='sasarankbumn',
            name='kode',
            field=models.CharField(max_length=50, unique=True, verbose_name='Kode'),
        ),
        migrations.AlterField(
            model_name='sasarankbumn',
            name='nama',
            field=models.CharField(max_length=255, verbose_name='Nama Sasaran KBUMN'),
        ),
        migrations.AlterField(
            model_name='taksonomit3',
            name='aktif',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='taksonomit3',
            name='deskripsi',
            field=models.TextField(blank=True, null=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='taksonomit3',
            name='kode',
            field=models.CharField(max_length=50, unique=True, verbose_name='Kode'),
        ),
        migrations.AlterField(
            model_name='taksonomit3',
            name='nama',
            field=models.CharField(max_length=255, verbose_name='Nama Taksonomi T3'),
        ),
        migrations.AddConstraint(
            model_name='bagiankontrakmanajemen',
            constraint=models.UniqueConstraint(fields=('kontrak', 'kode_bagian'), name='unik_bagian_per_kontrak'),
        ),
        migrations.AddConstraint(
            model_name='itemkontrakmanajemen',
            constraint=models.UniqueConstraint(fields=('bagian', 'no_urut'), name='unik_item_kontrak_per_bagian'),
        ),
        migrations.AddConstraint(
            model_name='kontrakmanajemen',
            constraint=models.UniqueConstraint(fields=('judul', 'tahun', 'unit_bisnis'), name='unik_kontrak_manajemen_per_tahun_unit'),
        ),
        migrations.AddConstraint(
            model_name='kpmritem',
            constraint=models.UniqueConstraint(fields=('summary', 'reassessment_item'), name='unik_kpmr_item_per_summary'),
        ),
        migrations.AddConstraint(
            model_name='kpmritem',
            constraint=models.UniqueConstraint(fields=('summary', 'no_item'), name='unik_no_item_kpmr_per_summary'),
        ),
        migrations.AddConstraint(
            model_name='reassessmentitem',
            constraint=models.UniqueConstraint(fields=('summary', 'no_item'), name='unik_reassessment_item_per_summary'),
        ),
        migrations.AddConstraint(
            model_name='reassessmentitem',
            constraint=models.UniqueConstraint(fields=('summary', 'no_risiko'), name='unik_reassessment_risiko_per_summary'),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatitem',
            name='kategori_risiko',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.kategoririsiko', verbose_name='Kategori Risiko'),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatitem',
            name='taksonomi_t3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.taksonomit3', verbose_name='Taksonomi Risiko PLN (T3)'),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatsumber',
            name='reassessment_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mendukung_risiko_korporat', to='risk.reassessmentitem', verbose_name='Risiko Bidang / Unit (Re-Assessment)'),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatsumber',
            name='risiko_korporat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sumber_risiko', to='risk.profilrisikokorporatitem', verbose_name='Risiko Korporat'),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatitem',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='risk.profilrisikokorporatsummary', verbose_name='Summary'),
        ),
        migrations.AddConstraint(
            model_name='profilrisikokorporatsumber',
            constraint=models.UniqueConstraint(fields=('risiko_korporat', 'reassessment_item'), name='unik_sumber_risiko_korporat'),
        ),
        migrations.AddConstraint(
            model_name='profilrisikokorporatitem',
            constraint=models.UniqueConstraint(fields=('summary', 'no_item'), name='unik_item_profil_risiko_korporat'),
        ),
    ]
