# Generated by Django 6.0.3 on 2026-04-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0008_profilrisikokorporatitem_profilrisikokorporatsumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemkontrakmanajemen',
            name='formula',
            field=models.TextField(blank=True, null=True, verbose_name='Formula'),
        ),
        migrations.AddField(
            model_name='itemkontrakmanajemen',
            name='satuan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Satuan'),
        ),
    ]
