# Generated by Django 6.0.3 on 2026-04-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0009_itemkontrakmanajemen_formula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemkontrakmanajemen',
            name='target',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Target'),
        ),
    ]
