# Generated by Django 6.0.3 on 2026-04-02 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0010_itemkontrakmanajemen_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterEfektivitasKontrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('aktif', models.BooleanField(default=True)),
                ('urutan', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'MASTER — Penilaian Efektivitas Kontrol',
                'verbose_name_plural': 'MASTER — Penilaian Efektivitas Kontrol',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='MasterJenisExistingControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('aktif', models.BooleanField(default=True)),
                ('urutan', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'MASTER — Jenis Existing Control',
                'verbose_name_plural': 'MASTER — Jenis Existing Control',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.AddField(
            model_name='profilrisikokorporatitem',
            name='existing_control',
            field=models.TextField(blank=True, null=True, verbose_name='Existing Control'),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatitem',
            name='key_risk_indicators',
            field=models.TextField(blank=True, null=True, verbose_name='Key Risk Indicators'),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatitem',
            name='kode_penyebab_risiko',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kode Penyebab Risiko'),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatitem',
            name='no_penyebab_risiko',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='No Penyebab Risiko'),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatitem',
            name='penyebab_risiko',
            field=models.TextField(blank=True, null=True, verbose_name='Penyebab Risiko'),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatitem',
            name='threshold_aman',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Threshold KRI - Aman'),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatitem',
            name='threshold_bahaya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Threshold KRI - Bahaya'),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatitem',
            name='threshold_hati_hati',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Threshold KRI - Hati-Hati'),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatitem',
            name='unit_satuan_kri',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unit Satuan KRI'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='existing_control',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='key_risk_indicators',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='kode_penyebab_risiko',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='no_penyebab_risiko',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='penyebab_risiko',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='threshold_aman',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='threshold_bahaya',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='threshold_hati_hati',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='unit_satuan_kri',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatitem',
            name='penilaian_efektivitas_kontrol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.masterefektivitaskontrol', verbose_name='Penilaian Efektivitas Kontrol'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='penilaian_efektivitas_kontrol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.masterefektivitaskontrol'),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatitem',
            name='jenis_existing_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.masterjenisexistingcontrol', verbose_name='Jenis Existing Control'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='jenis_existing_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.masterjenisexistingcontrol'),
        ),
    ]
