# Generated by Django 6.0.3 on 2026-04-02 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0011_masterefektivitaskontrol_masterjenisexistingcontrol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterJenisProgramRKAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150, unique=True)),
                ('aktif', models.BooleanField(default=True)),
                ('urutan', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'MASTER — Jenis Program Dalam RKAP',
                'verbose_name_plural': 'MASTER — Jenis Program Dalam RKAP',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='MasterJenisRencanaPerlakuanRisiko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150, unique=True)),
                ('aktif', models.BooleanField(default=True)),
                ('urutan', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'MASTER — Jenis Rencana Perlakuan Risiko',
                'verbose_name_plural': 'MASTER — Jenis Rencana Perlakuan Risiko',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='MasterKategoriDampak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('aktif', models.BooleanField(default=True)),
                ('urutan', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'MASTER — Kategori Dampak',
                'verbose_name_plural': 'MASTER — Kategori Dampak',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='MasterOpsiPerlakuanRisiko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('aktif', models.BooleanField(default=True)),
                ('urutan', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'MASTER — Opsi Perlakuan Risiko',
                'verbose_name_plural': 'MASTER — Opsi Perlakuan Risiko',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='MasterPosAnggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('aktif', models.BooleanField(default=True)),
                ('urutan', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'MASTER — Pos Anggaran',
                'verbose_name_plural': 'MASTER — Pos Anggaran',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='MasterSkalaDampak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('aktif', models.BooleanField(default=True)),
                ('urutan', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'MASTER — Skala Dampak',
                'verbose_name_plural': 'MASTER — Skala Dampak',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='MasterSkalaProbabilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('aktif', models.BooleanField(default=True)),
                ('urutan', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'MASTER — Skala Probabilitas',
                'verbose_name_plural': 'MASTER — Skala Probabilitas',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.AlterModelOptions(
            name='reassessmentitem',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='reassessmentitem',
            name='unik_reassessment_item_per_summary',
        ),
        migrations.RemoveConstraint(
            model_name='reassessmentitem',
            name='unik_reassessment_risiko_per_summary',
        ),
        migrations.RemoveField(
            model_name='profilrisikokorporatitem',
            name='kode_penyebab_risiko',
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='asumsi_perhitungan_dampak',
            field=models.TextField(blank=True, null=True, verbose_name='Asumsi Perhitungan Dampak Kuantitatif / Penjelasan Dampak Kualitatif'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='biaya_perlakuan_risiko',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Biaya Perlakuan Risiko'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='deskripsi_dampak',
            field=models.TextField(blank=True, null=True, verbose_name='Deskripsi Dampak'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='level_nilai_risiko',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Level Nilai Risiko'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='nilai_dampak',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Nilai Dampak'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='nilai_eksposur_risiko',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Nilai Eksposur Risiko'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='nilai_probabilitas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Nilai Probabilitas'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='output_perlakuan_risiko',
            field=models.TextField(blank=True, null=True, verbose_name='Output Perlakuan Risiko'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='perkiraan_waktu_terpapar_risiko',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Perkiraan Waktu Terpapar Risiko'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='pic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PIC'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='prk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PRK'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='rencana_perlakuan_risiko',
            field=models.TextField(blank=True, null=True, verbose_name='Rencana Perlakuan Risiko'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='skala_risiko',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Skala Risiko'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='timeline_1',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Bulan 1'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='timeline_10',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Bulan 10'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='timeline_11',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Bulan 11'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='timeline_12',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Bulan 12'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='timeline_2',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Bulan 2'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='timeline_3',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Bulan 3'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='timeline_4',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Bulan 4'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='timeline_5',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Bulan 5'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='timeline_6',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Bulan 6'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='timeline_7',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Bulan 7'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='timeline_8',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Bulan 8'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='timeline_9',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Bulan 9'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='jenis_program_dalam_rkap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.masterjenisprogramrkap', verbose_name='Jenis Program Dalam RKAP'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='jenis_rencana_perlakuan_risiko',
            field=models.ManyToManyField(blank=True, to='risk.masterjenisrencanaperlakuanrisiko', verbose_name='Jenis Rencana Perlakuan Risiko'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='kategori_dampak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.masterkategoridampak', verbose_name='Kategori Dampak'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='opsi_perlakuan_risiko',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.masteropsiperlakuanrisiko', verbose_name='Opsi Perlakuan Risiko'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='pos_anggaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.masterposanggaran', verbose_name='Pos Anggaran'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='skala_dampak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.masterskaladampak', verbose_name='Skala Dampak'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='skala_probabilitas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.masterskalaprobabilitas', verbose_name='Skala Probabilitas'),
        ),
        migrations.RemoveField(
            model_name='reassessmentitem',
            name='kode_penyebab_risiko',
        ),
    ]
