# Generated by Django 6.0.3 on 2026-04-02 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0012_masterjenisprogramrkap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reassessmentitem',
            name='skala_dampak',
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='skala_dampak_q1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dampak_q1', to='risk.masterskaladampak', verbose_name='Skala Dampak Q1'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='skala_dampak_q2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dampak_q2', to='risk.masterskaladampak', verbose_name='Skala Dampak Q2'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='skala_dampak_q3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dampak_q3', to='risk.masterskaladampak', verbose_name='Skala Dampak Q3'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='skala_dampak_q4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dampak_q4', to='risk.masterskaladampak', verbose_name='Skala Dampak Q4'),
        ),
    ]
