# Generated by Django 6.0.3 on 2026-04-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0013_remove_reassessmentitem_skala_dampak_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reassessmentitem',
            name='nilai_dampak',
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='nilai_dampak_q1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Nilai Dampak Q1'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='nilai_dampak_q2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Nilai Dampak Q2'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='nilai_dampak_q3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Nilai Dampak Q3'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='nilai_dampak_q4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Nilai Dampak Q4'),
        ),
    ]
