# Generated by Django 6.0.3 on 2026-04-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0014_remove_reassessmentitem_nilai_dampak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reassessmentitem',
            name='nilai_dampak',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Nilai Dampak'),
        ),
    ]
