# Generated by Django 6.0.3 on 2026-04-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0015_reassessmentitem_nilai_dampak'),
    ]

    operations = [
        migrations.AddField(
            model_name='reassessmentitem',
            name='skala_risiko_q1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Skala Risiko Q1'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='skala_risiko_q2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Skala Risiko Q2'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='skala_risiko_q3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Skala Risiko Q3'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='skala_risiko_q4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Skala Risiko Q4'),
        ),
    ]
