# Generated by Django 6.0.3 on 2026-04-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0016_reassessmentitem_skala_risiko_q1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reassessmentitem',
            name='nilai_probabilitas_q1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nilai Probabilitas Q1'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='nilai_probabilitas_q2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nilai Probabilitas Q2'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='nilai_probabilitas_q3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nilai Probabilitas Q3'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='nilai_probabilitas_q4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nilai Probabilitas Q4'),
        ),
    ]
