# Generated by Django 6.0.3 on 2026-04-03 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('risk', '0017_reassessmentitem_nilai_probabilitas_q1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reassessmentitem',
            options={'ordering': ['summary', 'no_item'], 'verbose_name': 'Item Risiko Unit/Bidang', 'verbose_name_plural': 'TRANSAKSI UNIT — Item Re-Assessment'},
        ),
        migrations.RemoveField(
            model_name='reassessmentitem',
            name='nilai_eksposur_risiko',
        ),
        migrations.RemoveField(
            model_name='reassessmentitem',
            name='skala_risiko',
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='existing_control',
            field=models.TextField(blank=True, null=True, verbose_name='Existing Control'),
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='jenis_existing_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.masterjenisexistingcontrol', verbose_name='Jenis Existing Control'),
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='key_risk_indicators',
            field=models.TextField(blank=True, null=True, verbose_name='Key Risk Indicators'),
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='nilai_probabilitas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nilai Probabilitas'),
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='no_penyebab_risiko',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='No Penyebab Risiko'),
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='penilaian_efektivitas_kontrol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.masterefektivitaskontrol', verbose_name='Penilaian Efektivitas Kontrol'),
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='penyebab_risiko',
            field=models.TextField(blank=True, null=True, verbose_name='Penyebab Risiko'),
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='threshold_aman',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Threshold Aman'),
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='threshold_bahaya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Threshold Bahaya'),
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='threshold_hati_hati',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Threshold Hati-Hati'),
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='unit_satuan_kri',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unit Satuan KRI'),
        ),
        migrations.AddConstraint(
            model_name='reassessmentitem',
            constraint=models.UniqueConstraint(fields=('summary', 'no_item'), name='unik_reassessment_item_per_summary'),
        ),
        migrations.AddConstraint(
            model_name='reassessmentitem',
            constraint=models.UniqueConstraint(fields=('summary', 'no_risiko'), name='unik_reassessment_risiko_per_summary'),
        ),
    ]
