# Generated by Django 6.0.3 on 2026-04-04 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0018_alter_reassessmentitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reassessmentitem',
            name='skala_probabilitas_q1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='probabilitas_q1', to='risk.masterskalaprobabilitas', verbose_name='Skala Probabilitas Q1'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='skala_probabilitas_q2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='probabilitas_q2', to='risk.masterskalaprobabilitas', verbose_name='Skala Probabilitas Q2'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='skala_probabilitas_q3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='probabilitas_q3', to='risk.masterskalaprobabilitas', verbose_name='Skala Probabilitas Q3'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='skala_probabilitas_q4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='probabilitas_q4', to='risk.masterskalaprobabilitas', verbose_name='Skala Probabilitas Q4'),
        ),
    ]
