# Generated by Django 6.0.3 on 2026-04-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0019_reassessmentitem_skala_probabilitas_q1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reassessmentitem',
            name='eksposur_risiko_q1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Eksposur Risiko Q1'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='eksposur_risiko_q2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Eksposur Risiko Q2'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='eksposur_risiko_q3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Eksposur Risiko Q3'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='eksposur_risiko_q4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Eksposur Risiko Q4'),
        ),
    ]
