# Generated by Django 6.0.3 on 2026-04-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0020_reassessmentitem_eksposur_risiko_q1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reassessmentitem',
            name='level_nilai_risiko',
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='level_nilai_risiko_q1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Level Risiko Q1'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='level_nilai_risiko_q2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Level Risiko Q2'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='level_nilai_risiko_q3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Level Risiko Q3'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='level_nilai_risiko_q4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Level Risiko Q4'),
        ),
    ]
