# Generated by Django 6.0.3 on 2026-04-05 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0022_risk_matrix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reassessmentsummary',
            name='risk_matrix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reassessment_summaries', to='risk.riskmatrix', verbose_name='Matriks Risiko'),
        ),
    ]
