# Generated by Django 6.0.3 on 2026-04-05 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('risk', '0023_alter_reassessmentsummary_risk_matrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='RKMSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul RKM')),
                ('tahun', models.PositiveIntegerField(verbose_name='Tahun')),
                ('bulan', models.PositiveSmallIntegerField(verbose_name='Bulan')),
                ('tanggal_mulai', models.DateField(blank=True, null=True, verbose_name='Tanggal Mulai')),
                ('tanggal_selesai', models.DateField(blank=True, null=True, verbose_name='Tanggal Selesai')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Final', 'Final')], default='Draft', max_length=20, verbose_name='Status')),
                ('pic', models.CharField(blank=True, max_length=255, null=True, verbose_name='PIC')),
                ('deadline_pengajuan', models.DateField(blank=True, null=True, verbose_name='Deadline Pengajuan Re-Assessment')),
                ('tanggal_pengajuan', models.DateField(blank=True, null=True, verbose_name='Tanggal Pengajuan')),
                ('status_pengajuan', models.CharField(choices=[('Belum', 'Belum'), ('Diajukan', 'Diajukan'), ('Terlambat', 'Terlambat'), ('Disetujui', 'Disetujui')], default='Belum', max_length=20, verbose_name='Status Pengajuan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('kontrak_manajemen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rkm_summary', to='risk.kontrakmanajemen', verbose_name='Kontrak Manajemen')),
                ('unit_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rkm_summary', to='auth.group', verbose_name='Bidang / Unit Bisnis')),
            ],
            options={
                'verbose_name': 'RKM Unit/Bidang',
                'verbose_name_plural': 'TRANSAKSI UNIT — RKM',
                'ordering': ['-tahun', 'bulan', 'judul'],
            },
        ),
        migrations.CreateModel(
            name='RKMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_item', models.PositiveIntegerField(verbose_name='No Item')),
                ('sasaran', models.TextField(blank=True, null=True, verbose_name='Sasaran / KPI')),
                ('target_bulanan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Target Bulanan')),
                ('realisasi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Realisasi')),
                ('deviasi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Deviasi')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('km_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rkm_item', to='risk.itemkontrakmanajemen', verbose_name='Item KM')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='risk.rkmsummary', verbose_name='Summary RKM')),
            ],
            options={
                'verbose_name': 'Item RKM',
                'verbose_name_plural': 'TRANSAKSI UNIT — Item RKM',
                'ordering': ['summary', 'no_item'],
            },
        ),
        migrations.AddField(
            model_name='reassessmentsummary',
            name='rkm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reassessments', to='risk.rkmsummary', verbose_name='RKM'),
        ),
        migrations.AddConstraint(
            model_name='rkmsummary',
            constraint=models.UniqueConstraint(fields=('tahun', 'bulan', 'unit_bisnis', 'kontrak_manajemen'), name='unik_rkm_per_bulan_unit_km'),
        ),
        migrations.AddConstraint(
            model_name='rkmitem',
            constraint=models.UniqueConstraint(fields=('summary', 'no_item'), name='unik_item_rkm_per_summary'),
        ),
        migrations.AddConstraint(
            model_name='rkmitem',
            constraint=models.UniqueConstraint(fields=('summary', 'km_item'), name='unik_km_item_per_rkm'),
        ),
    ]
