# Generated by Django 6.0.3 on 2026-04-07 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0024_rkmsummary_rkmitem_reassessmentsummary_rkm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilrisikokorporatitem',
            name='no_penyebab_risiko',
        ),
        migrations.RemoveField(
            model_name='profilrisikokorporatitem',
            name='penyebab_risiko',
        ),
        migrations.AddField(
            model_name='profilrisikokorporatitem',
            name='deskripsi_peristiwa_risiko',
            field=models.TextField(blank=True, null=True, verbose_name='Deskripsi Peristiwa Risiko'),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatitem',
            name='kode_bumn',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kode BUMN'),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatitem',
            name='nama_bumn',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nama BUMN'),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatitem',
            name='no_risiko',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='No Risiko'),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatitem',
            name='sasaran_kbumn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.sasarankbumn', verbose_name='Sasaran KBUMN'),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatsumber',
            name='kode_penyebab_risiko',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kode Penyebab Risiko'),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatsumber',
            name='no_penyebab_risiko',
            field=models.CharField(blank=True, max_length=10, verbose_name='No Penyebab Risiko'),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatsumber',
            name='penyebab_risiko',
            field=models.TextField(blank=True, null=True, verbose_name='Penyebab Risiko'),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatsummary',
            name='kode_perusahaan',
            field=models.CharField(default='PLNBATAM', max_length=50, verbose_name='Kode BUMN'),
        ),
        migrations.AlterField(
            model_name='profilrisikokorporatitem',
            name='kategori_risiko',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.kategoririsiko', verbose_name='Kategori Risiko BUMN'),
        ),
        migrations.AlterField(
            model_name='profilrisikokorporatitem',
            name='peristiwa_risiko',
            field=models.TextField(verbose_name='Peristiwa Risiko'),
        ),
        migrations.AlterField(
            model_name='profilrisikokorporatitem',
            name='sasaran_korporat',
            field=models.TextField(verbose_name='Sasaran BUMN'),
        ),
        migrations.AlterField(
            model_name='profilrisikokorporatitem',
            name='taksonomi_t3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.taksonomit3', verbose_name='Kategori Risiko T2 & T3'),
        ),
        migrations.AlterField(
            model_name='profilrisikokorporatsummary',
            name='nama_perusahaan',
            field=models.CharField(default='PT PLN Batam', max_length=200, verbose_name='Nama BUMN'),
        ),
        migrations.AddConstraint(
            model_name='profilrisikokorporatitem',
            constraint=models.UniqueConstraint(fields=('summary', 'no_risiko'), name='unik_no_risiko_korporat_per_summary'),
        ),
    ]
