# Generated by Django 6.0.3 on 2026-04-07 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_masterbumn'),
        ('risk', '0025_remove_profilrisikokorporatitem_no_penyebab_risiko_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilrisikokorporatitem',
            name='kode_bumn',
        ),
        migrations.RemoveField(
            model_name='profilrisikokorporatitem',
            name='nama_bumn',
        ),
        migrations.AddField(
            model_name='profilrisikokorporatitem',
            name='bumn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.masterbumn', verbose_name='Nama BUMN'),
        ),
    ]
