# Generated by Django 6.0.3 on 2026-04-07 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_masterbumn'),
        ('risk', '0026_remove_profilrisikokorporatitem_kode_bumn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilrisikokorporatitem',
            name='bumn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='masterdata.masterbumn', verbose_name='Nama BUMN'),
            preserve_default=False,
        ),
    ]
