# Generated by Django 6.0.3 on 2026-04-08 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_masterbumn'),
        ('risk', '0027_alter_profilrisikokorporatitem_bumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilrisikokorporatitem',
            name='deskripsi_dampak',
            field=models.TextField(blank=True, null=True, verbose_name='Deskripsi Dampak'),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatitem',
            name='kategori_dampak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.masterkategoridampak', verbose_name='Kategori Dampak'),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatitem',
            name='penyebab_risiko',
            field=models.TextField(blank=True, null=True, verbose_name='Penyebab Risiko'),
        ),
        migrations.AddField(
            model_name='profilrisikokorporatitem',
            name='perkiraan_waktu_terpapar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Perkiraan Waktu Terpapar Risiko'),
        ),
        migrations.AlterField(
            model_name='profilrisikokorporatitem',
            name='bumn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='masterdata.masterbumn', verbose_name='Nama BUMN'),
        ),
    ]
