# Generated by Django 6.0.3 on 2026-04-08 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0028_profilrisikokorporatitem_deskripsi_dampak_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilrisikokorporatitem',
            name='deskripsi_dampak',
        ),
        migrations.RemoveField(
            model_name='profilrisikokorporatitem',
            name='existing_control',
        ),
        migrations.RemoveField(
            model_name='profilrisikokorporatitem',
            name='jenis_existing_control',
        ),
        migrations.RemoveField(
            model_name='profilrisikokorporatitem',
            name='kategori_dampak',
        ),
        migrations.RemoveField(
            model_name='profilrisikokorporatitem',
            name='key_risk_indicators',
        ),
        migrations.RemoveField(
            model_name='profilrisikokorporatitem',
            name='penilaian_efektivitas_kontrol',
        ),
        migrations.RemoveField(
            model_name='profilrisikokorporatitem',
            name='penyebab_risiko',
        ),
        migrations.RemoveField(
            model_name='profilrisikokorporatitem',
            name='perkiraan_waktu_terpapar',
        ),
        migrations.RemoveField(
            model_name='profilrisikokorporatitem',
            name='perlakuan_risiko',
        ),
        migrations.RemoveField(
            model_name='profilrisikokorporatitem',
            name='threshold_aman',
        ),
        migrations.RemoveField(
            model_name='profilrisikokorporatitem',
            name='threshold_bahaya',
        ),
        migrations.RemoveField(
            model_name='profilrisikokorporatitem',
            name='threshold_hati_hati',
        ),
        migrations.RemoveField(
            model_name='profilrisikokorporatitem',
            name='unit_satuan_kri',
        ),
        migrations.CreateModel(
            name='ProfilRisikoKorporatPenyebab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.PositiveIntegerField(default=1, verbose_name='Urutan')),
                ('no_penyebab_risiko', models.CharField(blank=True, max_length=5, verbose_name='No Penyebab')),
                ('kode_penyebab_risiko', models.CharField(blank=True, max_length=100, verbose_name='Kode Penyebab Risiko')),
                ('penyebab_risiko', models.TextField(blank=True, null=True)),
                ('key_risk_indicators', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_satuan_kri', models.CharField(blank=True, max_length=50, null=True)),
                ('threshold_aman', models.CharField(blank=True, max_length=50, null=True)),
                ('threshold_hati_hati', models.CharField(blank=True, max_length=50, null=True)),
                ('threshold_bahaya', models.CharField(blank=True, max_length=50, null=True)),
                ('existing_control', models.TextField(blank=True, null=True)),
                ('deskripsi_dampak', models.TextField(blank=True, null=True)),
                ('perkiraan_waktu_terpapar', models.CharField(blank=True, max_length=100, null=True)),
                ('jenis_existing_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.masterjenisexistingcontrol')),
                ('kategori_dampak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.masterkategoridampak')),
                ('penilaian_efektivitas_kontrol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.masterefektivitaskontrol')),
                ('risiko_korporat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_penyebab', to='risk.profilrisikokorporatitem', verbose_name='Risiko Korporat')),
            ],
            options={
                'verbose_name': 'Penyebab Risiko',
                'verbose_name_plural': 'Penyebab Risiko (Multi Input)',
                'ordering': ['risiko_korporat', 'urutan'],
            },
        ),
    ]
