# Generated by Django 6.0.3 on 2026-04-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0029_remove_profilrisikokorporatitem_deskripsi_dampak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilrisikokorporatpenyebab',
            name='key_risk_indicators',
            field=models.TextField(blank=True, null=True, verbose_name='Key Risk Indicators'),
        ),
    ]
