# Generated by Django 6.0.3 on 2026-04-09 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0032_penugasanunitbisnis'),
    ]

    operations = [
        migrations.CreateModel(
            name='RencanaPerlakuanRisikoKorporat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.PositiveIntegerField(default=1, verbose_name='Urutan')),
                ('rencana_perlakuan_risiko', models.TextField(blank=True, null=True, verbose_name='Rencana Perlakuan Risiko')),
                ('output_perlakuan_risiko', models.TextField(blank=True, null=True, verbose_name='Output Perlakuan Risiko')),
                ('biaya_perlakuan_risiko', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Biaya Perlakuan Risiko')),
                ('prk', models.CharField(blank=True, max_length=100, null=True, verbose_name='PRK')),
                ('pic', models.CharField(blank=True, max_length=255, null=True, verbose_name='PIC')),
                ('timeline_1', models.PositiveSmallIntegerField(default=0, verbose_name='Bulan 1')),
                ('timeline_2', models.PositiveSmallIntegerField(default=0, verbose_name='Bulan 2')),
                ('timeline_3', models.PositiveSmallIntegerField(default=0, verbose_name='Bulan 3')),
                ('timeline_4', models.PositiveSmallIntegerField(default=0, verbose_name='Bulan 4')),
                ('timeline_5', models.PositiveSmallIntegerField(default=0, verbose_name='Bulan 5')),
                ('timeline_6', models.PositiveSmallIntegerField(default=0, verbose_name='Bulan 6')),
                ('timeline_7', models.PositiveSmallIntegerField(default=0, verbose_name='Bulan 7')),
                ('timeline_8', models.PositiveSmallIntegerField(default=0, verbose_name='Bulan 8')),
                ('timeline_9', models.PositiveSmallIntegerField(default=0, verbose_name='Bulan 9')),
                ('timeline_10', models.PositiveSmallIntegerField(default=0, verbose_name='Bulan 10')),
                ('timeline_11', models.PositiveSmallIntegerField(default=0, verbose_name='Bulan 11')),
                ('timeline_12', models.PositiveSmallIntegerField(default=0, verbose_name='Bulan 12')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('jenis_program_dalam_rkap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.masterjenisprogramrkap', verbose_name='Jenis Program Dalam RKAP')),
                ('jenis_rencana_perlakuan_risiko', models.ManyToManyField(blank=True, to='risk.masterjenisrencanaperlakuanrisiko', verbose_name='Jenis Rencana Perlakuan Risiko')),
                ('opsi_perlakuan_risiko', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.masteropsiperlakuanrisiko', verbose_name='Opsi Perlakuan Risiko')),
                ('pos_anggaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.masterposanggaran', verbose_name='Pos Anggaran')),
                ('risiko_korporat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rencana_perlakuan_items', to='risk.profilrisikokorporatitem', verbose_name='Risiko Korporat')),
            ],
            options={
                'verbose_name': 'Rencana Perlakuan Risiko Korporat',
                'verbose_name_plural': 'KORPORAT — Rencana Perlakuan Risiko',
                'ordering': ['risiko_korporat', 'urutan'],
            },
        ),
        migrations.CreateModel(
            name='RisikoInherenKuantitatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_dampak', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Nilai Dampak')),
                ('probabilitas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Probabilitas (%)')),
                ('eksposur', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Eksposur Risiko')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('risiko_korporat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inheren_kuantitatif', to='risk.profilrisikokorporatitem', verbose_name='Risiko Korporat')),
            ],
            options={
                'verbose_name': 'Risiko Inheren Kuantitatif',
                'verbose_name_plural': 'KORPORAT — Risiko Inheren Kuantitatif',
            },
        ),
    ]
