# Generated by Django 6.0.3 on 2026-04-09 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('risk', '0033_rencanaperlakuanrisikokorporat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KinerjaPeriode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveIntegerField(verbose_name='Tahun')),
                ('triwulan', models.PositiveSmallIntegerField(choices=[(1, 'TW1'), (2, 'TW2'), (3, 'TW3'), (4, 'TW4')], verbose_name='Triwulan')),
                ('skor_total', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Skor Total Kinerja')),
                ('rating', models.CharField(blank=True, choices=[('SANGAT_BAIK', 'Sangat Baik'), ('BAIK', 'Baik'), ('CUKUP', 'Cukup'), ('KURANG', 'Kurang'), ('BURUK', 'Buruk')], max_length=20, null=True, verbose_name='Rating Kinerja')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('unit_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kinerja_periode', to='auth.group', verbose_name='Bidang / Unit Bisnis')),
            ],
            options={
                'verbose_name': 'Kinerja Triwulanan',
                'verbose_name_plural': 'Kinerja Triwulanan',
                'ordering': ['-tahun', 'triwulan', 'unit_bisnis__name'],
            },
        ),
        migrations.CreateModel(
            name='KinerjaIndikator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(choices=[('KPI_KOLEGIAL', 'Capaian KPI Kolegial'), ('KEUANGAN', 'Capaian Kinerja Keuangan'), ('OPERASI', 'Capaian Kinerja Operasi/Produksi Utama')], max_length=30, verbose_name='Indikator')),
                ('bobot', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Bobot (%)')),
                ('hasil', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Hasil')),
                ('skor', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Skor')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indikator', to='risk.kinerjaperiode', verbose_name='Periode Kinerja')),
            ],
            options={
                'verbose_name': 'Kinerja — Indikator',
                'verbose_name_plural': 'Kinerja — Indikator',
                'ordering': ['periode', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='KPMRPeriode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveIntegerField(verbose_name='Tahun')),
                ('triwulan', models.PositiveSmallIntegerField(choices=[(1, 'TW1'), (2, 'TW2'), (3, 'TW3'), (4, 'TW4')], verbose_name='Triwulan')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=20, verbose_name='Status')),
                ('skor_total', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Skor Total KPMR')),
                ('rating', models.CharField(blank=True, choices=[('STRONG', 'Strong'), ('SATISFACTORY', 'Satisfactory'), ('FAIR', 'Fair'), ('MARGINAL', 'Marginal'), ('UNSATISFACTORY', 'Unsatisfactory')], max_length=20, null=True, verbose_name='Rating KPMR')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('diubah_pada', models.DateTimeField(auto_now=True, verbose_name='Diubah Pada')),
                ('unit_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kpmr_periode', to='auth.group', verbose_name='Bidang / Unit Bisnis')),
            ],
            options={
                'verbose_name': 'KPMR PLN — Periode',
                'verbose_name_plural': 'KPMR PLN — Periode',
                'ordering': ['-tahun', 'triwulan', 'unit_bisnis__name'],
            },
        ),
        migrations.CreateModel(
            name='KPMRIndikatorResmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(choices=[('I1', 'I1 - Pencapaian Nilai Eksposur Risiko vs Target Residual'), ('I2', 'I2 - Pencapaian Output Perlakuan Risiko vs Target Output'), ('I3', 'I3 - Realisasi Biaya Perlakuan Risiko vs Anggaran'), ('I4', 'I4 - Ketepatan Penilaian Risiko')], max_length=5, verbose_name='Kode')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Indikator')),
                ('bobot', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Bobot (%)')),
                ('hasil', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Hasil')),
                ('skor', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Skor')),
                ('dokumen_referensi', models.TextField(blank=True, null=True, verbose_name='Dokumen Referensi')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indikator_resmi', to='risk.kpmrperiode', verbose_name='Periode KPMR')),
            ],
            options={
                'verbose_name': 'KPMR PLN — Indikator',
                'verbose_name_plural': 'KPMR PLN — Indikator',
                'ordering': ['periode', 'kode'],
            },
        ),
        migrations.CreateModel(
            name='KompositRisikoTriwulan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor_kpmr', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('skor_kinerja', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('peringkat_komposit', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Peringkat Komposit')),
                ('catatan_review_spi', models.TextField(blank=True, null=True, verbose_name='Catatan Review SPI')),
                ('periode_kinerja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='komposit_risiko', to='risk.kinerjaperiode', verbose_name='Periode Kinerja')),
                ('periode_kpmr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='komposit_risiko', to='risk.kpmrperiode', verbose_name='Periode KPMR')),
            ],
            options={
                'verbose_name': 'Komposit Risiko Triwulan',
                'verbose_name_plural': 'Komposit Risiko Triwulan',
                'ordering': ['-periode_kpmr__tahun', 'periode_kpmr__triwulan'],
            },
        ),
        migrations.CreateModel(
            name='KPMRSubIndikatorResmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(choices=[('IDENTIFIKASI', 'Identifikasi Risiko'), ('KUANTIFIKASI', 'Kuantifikasi Risiko'), ('RENCANA', 'Rencana Perlakuan Risiko'), ('PRIORITISASI', 'Prioritisasi Risiko')], max_length=30, verbose_name='Kode')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Sub Indikator')),
                ('bobot', models.DecimalField(decimal_places=2, default=25, max_digits=5, verbose_name='Bobot (%)')),
                ('jawaban', models.CharField(blank=True, max_length=50, null=True, verbose_name='Jawaban / Opsi')),
                ('hasil', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Hasil')),
                ('skor', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Skor')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('indikator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subindikator', to='risk.kpmrindikatorresmi', verbose_name='Indikator KPMR')),
            ],
            options={
                'verbose_name': 'KPMR PLN — Sub Indikator',
                'verbose_name_plural': 'KPMR PLN — Sub Indikator',
                'ordering': ['indikator', 'kode'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveIntegerField(verbose_name='Tahun')),
                ('nomor_urut', models.PositiveSmallIntegerField(verbose_name='No')),
                ('nama_program', models.CharField(max_length=255, verbose_name='Program')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Roadmap MR — Program',
                'verbose_name_plural': 'Roadmap MR — Program',
                'ordering': ['tahun', 'nomor_urut'],
                'constraints': [models.UniqueConstraint(fields=('tahun', 'nomor_urut'), name='unik_nomor_roadmap_per_tahun')],
            },
        ),
        migrations.CreateModel(
            name='RoadmapPenilaianSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveIntegerField(verbose_name='Tahun')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')], verbose_name='Semester')),
                ('nilai_kuantitas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nilai_kualitas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nilai_waktu', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nilai_program', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('unit_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roadmap_penilaian_semester', to='auth.group', verbose_name='Bidang / Unit Bisnis')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_semester', to='risk.roadmapprogram', verbose_name='Program Roadmap')),
            ],
            options={
                'verbose_name': 'Roadmap MR — Penilaian Semester',
                'verbose_name_plural': 'Roadmap MR — Penilaian Semester',
                'ordering': ['-tahun', 'semester', 'unit_bisnis__name', 'program__nomor_urut'],
            },
        ),
        migrations.AddConstraint(
            model_name='kinerjaperiode',
            constraint=models.UniqueConstraint(fields=('tahun', 'triwulan', 'unit_bisnis'), name='unik_kinerja_periode_per_triwulan_unit'),
        ),
        migrations.AddConstraint(
            model_name='kinerjaindikator',
            constraint=models.UniqueConstraint(fields=('periode', 'nama'), name='unik_indikator_kinerja_per_periode'),
        ),
        migrations.AddConstraint(
            model_name='kpmrperiode',
            constraint=models.UniqueConstraint(fields=('tahun', 'triwulan', 'unit_bisnis'), name='unik_kpmr_periode_per_triwulan_unit'),
        ),
        migrations.AddConstraint(
            model_name='kpmrindikatorresmi',
            constraint=models.UniqueConstraint(fields=('periode', 'kode'), name='unik_indikator_kpmr_resmi_per_periode'),
        ),
        migrations.AddConstraint(
            model_name='kpmrsubindikatorresmi',
            constraint=models.UniqueConstraint(fields=('indikator', 'kode'), name='unik_subindikator_kpmr_resmi_per_indikator'),
        ),
        migrations.AddConstraint(
            model_name='roadmappenilaiansemester',
            constraint=models.UniqueConstraint(fields=('tahun', 'semester', 'unit_bisnis', 'program'), name='unik_penilaian_roadmap_per_semester_unit_program'),
        ),
    ]
