# Generated by Django 6.0.3 on 2026-04-10 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('risk', '0034_kinerjaperiode_kinerjaindikator_kpmrperiode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reassessmentitem',
            name='unit_bisnis',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='reassessment_item', to='auth.group', verbose_name='Bidang / Unit Bisnis'),
        ),
    ]
