# Generated by Django 6.0.3 on 2026-04-10 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('risk', '0035_alter_reassessmentitem_unit_bisnis'),
    ]

    operations = [
        migrations.CreateModel(
            name='RKAPItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveIntegerField(verbose_name='Tahun')),
                ('kode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kode RKAP')),
                ('sasaran', models.CharField(max_length=255, verbose_name='Sasaran RKAP')),
                ('indikator', models.CharField(blank=True, max_length=255, null=True, verbose_name='Indikator')),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Target')),
                ('satuan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Satuan')),
                ('asumsi', models.TextField(blank=True, null=True, verbose_name='Asumsi / Driver RKAP')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('unit_penanggung_jawab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rkap_items', to='auth.group', verbose_name='Unit Penanggung Jawab')),
            ],
            options={
                'verbose_name': 'RKAP — Item',
                'verbose_name_plural': 'RKAP — Item',
                'ordering': ['-tahun', 'kode', 'sasaran'],
            },
        ),
        migrations.AddField(
            model_name='profilrisikokorporatitem',
            name='rkap_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risiko_korporat_items', to='risk.rkapitem', verbose_name='Sumber Target RKAP'),
        ),
        migrations.AddConstraint(
            model_name='rkapitem',
            constraint=models.UniqueConstraint(fields=('tahun', 'kode', 'sasaran'), name='unik_rkap_item_per_tahun_kode_sasaran'),
        ),
    ]
