# Generated by Django 6.0.3 on 2026-05-10 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('risk', '0036_rkapitem_profilrisikokorporatitem_rkap_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilrisikokorporatpenyebab',
            name='pemilik_risiko',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pemilik_penyebab_risiko_korporat', to='auth.group', verbose_name='Pemilik Risiko'),
        ),
    ]
