# Generated by Django 6.0.3 on 2026-05-11 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0037_profilrisikokorporatpenyebab_pemilik_risiko'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateBagianKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_bagian', models.CharField(max_length=10)),
                ('nama_bagian', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Bagian Template KM',
                'verbose_name_plural': 'Bagian Template KM',
                'ordering': ['kode_bagian'],
            },
        ),
        migrations.CreateModel(
            name='TemplateKontrakManajemen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField(unique=True)),
                ('nama', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Template Kontrak Manajemen',
                'verbose_name_plural': 'Template Kontrak Manajemen',
                'ordering': ['-tahun'],
            },
        ),
        migrations.CreateModel(
            name='TemplateItemKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_urut', models.PositiveIntegerField()),
                ('indikator_kinerja_kunci', models.TextField()),
                ('formula', models.TextField(blank=True, null=True)),
                ('satuan', models.CharField(blank=True, max_length=100, null=True)),
                ('target', models.CharField(blank=True, max_length=255, null=True)),
                ('bobot', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bagian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_list', to='risk.templatebagiankm')),
            ],
            options={
                'verbose_name': 'Item Template KM',
                'verbose_name_plural': 'Item Template KM',
                'ordering': ['no_urut'],
            },
        ),
        migrations.AddField(
            model_name='templatebagiankm',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bagian_list', to='risk.templatekontrakmanajemen'),
        ),
        migrations.AddField(
            model_name='kontrakmanajemen',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kontrak_list', to='risk.templatekontrakmanajemen'),
        ),
    ]
