# Generated by Django 6.0.3 on 2026-05-11 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0038_templatebagiankm_templatekontrakmanajemen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterBagianKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_bagian', models.CharField(max_length=10)),
                ('nama_bagian', models.CharField(max_length=255)),
                ('urutan', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'MASTER — Bagian KM',
                'verbose_name_plural': 'MASTER — Bagian KM',
                'ordering': ['template__tahun', 'urutan', 'kode_bagian'],
            },
        ),
        migrations.CreateModel(
            name='MasterTemplateKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField(unique=True)),
                ('nama', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'MASTER — Template KM',
                'verbose_name_plural': 'MASTER — Template KM',
                'ordering': ['-tahun'],
            },
        ),
        migrations.AddField(
            model_name='itemkontrakmanajemen',
            name='kontrak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_list', to='risk.kontrakmanajemen'),
        ),
        migrations.AddField(
            model_name='itemkontrakmanajemen',
            name='master_bagian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.masterbagiankm'),
        ),
        migrations.AddField(
            model_name='masterbagiankm',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bagian_list', to='risk.mastertemplatekm'),
        ),
        migrations.AlterField(
            model_name='kontrakmanajemen',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kontrak_list', to='risk.mastertemplatekm'),
        ),
    ]
