# Generated by Django 6.0.3 on 2026-05-11 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0039_masterbagiankm_mastertemplatekm_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemkontrakmanajemen',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='itemkontrakmanajemen',
            name='unik_item_kontrak_per_bagian',
        ),
        migrations.RemoveField(
            model_name='profilrisikokorporatitem',
            name='pemilik_risiko',
        ),
        migrations.AddField(
            model_name='itemkontrakmanajemen',
            name='polaritas',
            field=models.CharField(choices=[('positif', 'Positif'), ('negatif', 'Negatif')], default='positif', max_length=10),
        ),
        migrations.AlterField(
            model_name='itemkontrakmanajemen',
            name='bobot',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='itemkontrakmanajemen',
            name='formula',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemkontrakmanajemen',
            name='indikator_kinerja_kunci',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='itemkontrakmanajemen',
            name='kontrak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.kontrakmanajemen'),
        ),
        migrations.AlterField(
            model_name='itemkontrakmanajemen',
            name='master_bagian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.masterbagiankm'),
        ),
        migrations.AlterField(
            model_name='itemkontrakmanajemen',
            name='no_urut',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemkontrakmanajemen',
            name='satuan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemkontrakmanajemen',
            name='target',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='itemkontrakmanajemen',
            name='bagian',
        ),
    ]
