# Generated by Django 6.0.3 on 2026-05-12 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0040_alter_itemkontrakmanajemen_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrakmanajemen',
            name='pihak_kedua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='km_pihak_kedua', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kontrakmanajemen',
            name='pihak_pertama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='km_pihak_pertama', to=settings.AUTH_USER_MODEL),
        ),
    ]
