# Generated by Django 6.0.3 on 2026-05-12 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0041_kontrakmanajemen_pihak_kedua_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrakmanajemen',
            name='tanggal_kontrak',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Kontrak'),
        ),
        migrations.AlterField(
            model_name='kontrakmanajemen',
            name='pihak_kedua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='km_pihak_kedua', to=settings.AUTH_USER_MODEL, verbose_name='Pihak Kedua'),
        ),
        migrations.AlterField(
            model_name='kontrakmanajemen',
            name='pihak_pertama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='km_pihak_pertama', to=settings.AUTH_USER_MODEL, verbose_name='Pihak Pertama'),
        ),
        migrations.CreateModel(
            name='RiwayatJabatanUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=255, verbose_name='Jabatan')),
                ('tanggal_mulai', models.DateField(verbose_name='Tanggal Mulai')),
                ('tanggal_selesai', models.DateField(blank=True, null=True, verbose_name='Tanggal Selesai')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_jabatan', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Riwayat Jabatan User',
                'verbose_name_plural': 'MASTER — Riwayat Jabatan User',
                'ordering': ['user', '-tanggal_mulai'],
            },
        ),
    ]
