# Generated by Django 6.0.3 on 2026-05-13 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0042_kontrakmanajemen_tanggal_kontrak_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemkontrakmanajemen',
            options={'ordering': ['kontrak', 'master_bagian__urutan', 'no_urut'], 'verbose_name': 'Item Kontrak', 'verbose_name_plural': 'TRANSAKSI UNIT — Item Kontrak'},
        ),
    ]
