# Generated by Django 6.0.3 on 2026-05-13 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0044_remove_itemkontrakmanajemen_bagian'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemkontrakmanajemen',
            name='bagian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='risk.bagiankontrakmanajemen'),
        ),
    ]
