# Generated by Django 6.0.3 on 2026-05-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0045_itemkontrakmanajemen_bagian'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='itemkontrakmanajemen',
            constraint=models.UniqueConstraint(fields=('kontrak', 'master_bagian', 'no_urut'), name='unique_km_item_per_bagian'),
        ),
    ]
