# Generated by Django 6.0.3 on 2026-05-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('risk', '0046_itemkontrakmanajemen_unique_km_item_per_bagian'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reassessmentitem',
            options={'ordering': ['summary', 'no_item', 'no_risiko'], 'verbose_name': 'Item Risiko Unit/Bidang', 'verbose_name_plural': 'TRANSAKSI UNIT — Item Re-Assessment'},
        ),
        migrations.RemoveConstraint(
            model_name='reassessmentitem',
            name='unik_reassessment_item_per_summary',
        ),
        migrations.RemoveConstraint(
            model_name='reassessmentitem',
            name='unik_reassessment_risiko_per_summary',
        ),
        migrations.AddConstraint(
            model_name='reassessmentitem',
            constraint=models.UniqueConstraint(fields=('summary', 'no_item', 'no_risiko'), name='unik_reassessment_item_risiko_per_summary'),
        ),
    ]
