# Generated by Django 6.0.3 on 2026-05-23 23:36

from django.db import migrations, models


def seed_app_setting(apps, schema_editor):
    AppSetting = apps.get_model("risk", "AppSetting")
    AppSetting.objects.update_or_create(
        pk=1,
        defaults={
            "nama_aplikasi": "Manajemen Risiko PLN Batam",
            "logo": "system/logo/pln_batam_logo.png",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0047_alter_reassessmentitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_aplikasi', models.CharField(default='Manajemen Risiko PLN Batam', max_length=120, verbose_name='Nama Aplikasi')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='system/logo/', verbose_name='Logo PLN Batam')),
                ('diperbarui_pada', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
            ],
            options={
                'verbose_name': 'Pengaturan Aplikasi',
                'verbose_name_plural': 'PENGATURAN — Aplikasi',
            },
        ),
        migrations.RunPython(seed_app_setting, migrations.RunPython.noop),
    ]
