# Generated by Codex on 2026-05-26

from decimal import Decimal

from django.db import migrations, models


def seed_setting_defaults(apps, schema_editor):
    AppSetting = apps.get_model("risk", "AppSetting")
    AppSetting.objects.update_or_create(
        pk=1,
        defaults={
            "nama_aplikasi": "Manajemen Risiko PLN Batam",
            "subtitle_aplikasi": "Enterprise Risk Management",
            "logo": "system/logo/pln_batam_logo.png",
            "tampilkan_logo": True,
            "warna_header": "#3f7c91",
            "warna_teks_header": "#ffe45c",
            "ldap_aktif": True,
            "ldap_server": "ldap://10.28.0.154",
            "ldap_base_dn": "dc=plnbatam,dc=com",
            "ldap_domain": "PLNBATAM",
            "ldap_user_filter": "(sAMAccountName={username})",
            "ldap_email_domain": "plnbatam.com",
            "ldap_debug": False,
            "ai_aktif": False,
            "ai_provider": "openai",
            "ai_api_key": "",
            "ai_model": "gpt-4.1-mini",
            "ai_base_url": "https://api.openai.com/v1",
            "ai_temperature": Decimal("0.20"),
            "support_email": "",
            "footer_laporan": "PT PLN Batam - Manajemen Risiko",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0048_appsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsetting",
            name="ai_aktif",
            field=models.BooleanField(default=False, verbose_name="AI ChatGPT Aktif"),
        ),
        migrations.AddField(
            model_name="appsetting",
            name="ai_api_key",
            field=models.CharField(blank=True, default="", help_text="Simpan API key di sini hanya jika server sudah diamankan.", max_length=255, verbose_name="API Key AI"),
        ),
        migrations.AddField(
            model_name="appsetting",
            name="ai_base_url",
            field=models.URLField(blank=True, default="https://api.openai.com/v1", max_length=255, verbose_name="Base URL AI"),
        ),
        migrations.AddField(
            model_name="appsetting",
            name="ai_model",
            field=models.CharField(blank=True, default="gpt-4.1-mini", max_length=80, verbose_name="Model AI"),
        ),
        migrations.AddField(
            model_name="appsetting",
            name="ai_provider",
            field=models.CharField(choices=[("openai", "OpenAI / ChatGPT"), ("other", "Provider lain")], default="openai", max_length=30, verbose_name="Provider AI"),
        ),
        migrations.AddField(
            model_name="appsetting",
            name="ai_temperature",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.20"), max_digits=4, verbose_name="Temperature AI"),
        ),
        migrations.AddField(
            model_name="appsetting",
            name="footer_laporan",
            field=models.CharField(blank=True, default="PT PLN Batam - Manajemen Risiko", max_length=255, verbose_name="Footer Laporan"),
        ),
        migrations.AddField(
            model_name="appsetting",
            name="ldap_aktif",
            field=models.BooleanField(default=True, verbose_name="LDAP Aktif"),
        ),
        migrations.AddField(
            model_name="appsetting",
            name="ldap_base_dn",
            field=models.CharField(blank=True, default="dc=plnbatam,dc=com", max_length=255, verbose_name="LDAP Base DN"),
        ),
        migrations.AddField(
            model_name="appsetting",
            name="ldap_debug",
            field=models.BooleanField(default=False, verbose_name="Aktifkan Debug LDAP"),
        ),
        migrations.AddField(
            model_name="appsetting",
            name="ldap_domain",
            field=models.CharField(blank=True, default="PLNBATAM", max_length=100, verbose_name="LDAP Domain"),
        ),
        migrations.AddField(
            model_name="appsetting",
            name="ldap_email_domain",
            field=models.CharField(blank=True, default="plnbatam.com", max_length=120, verbose_name="Default Email Domain LDAP"),
        ),
        migrations.AddField(
            model_name="appsetting",
            name="ldap_server",
            field=models.CharField(blank=True, default="ldap://10.28.0.154", max_length=255, verbose_name="LDAP Server"),
        ),
        migrations.AddField(
            model_name="appsetting",
            name="ldap_user_filter",
            field=models.CharField(blank=True, default="(sAMAccountName={username})", max_length=255, verbose_name="LDAP User Search Filter"),
        ),
        migrations.AddField(
            model_name="appsetting",
            name="subtitle_aplikasi",
            field=models.CharField(blank=True, default="Enterprise Risk Management", max_length=180, verbose_name="Subtitle Aplikasi"),
        ),
        migrations.AddField(
            model_name="appsetting",
            name="support_email",
            field=models.EmailField(blank=True, default="", max_length=254, verbose_name="Email Support"),
        ),
        migrations.AddField(
            model_name="appsetting",
            name="tampilkan_logo",
            field=models.BooleanField(default=True, verbose_name="Tampilkan Logo di Header"),
        ),
        migrations.AddField(
            model_name="appsetting",
            name="warna_header",
            field=models.CharField(blank=True, default="#3f7c91", help_text="Contoh: #3f7c91", max_length=20, verbose_name="Warna Header"),
        ),
        migrations.AddField(
            model_name="appsetting",
            name="warna_teks_header",
            field=models.CharField(blank=True, default="#ffe45c", help_text="Contoh: #ffe45c", max_length=20, verbose_name="Warna Teks Header"),
        ),
        migrations.RunPython(seed_setting_defaults, migrations.RunPython.noop),
    ]
