# Generated by Django 6.0.3 on 2026-05-28 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0049_appsetting_system_integrations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rkapitem',
            options={'ordering': ['-tahun', 'kategori', 'subkategori', 'urutan', 'kode', 'sasaran'], 'verbose_name': 'RKAP — Item', 'verbose_name_plural': 'RKAP — Item'},
        ),
        migrations.AddField(
            model_name='rkapitem',
            name='bulan',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Isi 1-12 jika item ini adalah target bulanan.', null=True, verbose_name='Bulan'),
        ),
        migrations.AddField(
            model_name='rkapitem',
            name='halaman_sumber',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Halaman Sumber'),
        ),
        migrations.AddField(
            model_name='rkapitem',
            name='kategori',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='rkapitem',
            name='nilai_audited_2024',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Audited 2024'),
        ),
        migrations.AddField(
            model_name='rkapitem',
            name='nilai_unaudited_2025',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Unaudited 2025'),
        ),
        migrations.AddField(
            model_name='rkapitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Gunakan untuk detail bulanan atau rincian dari item RKAP utama.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='risk.rkapitem', verbose_name='Induk RKAP'),
        ),
        migrations.AddField(
            model_name='rkapitem',
            name='periode',
            field=models.CharField(choices=[('Tahunan', 'Tahunan'), ('Bulanan', 'Bulanan'), ('Triwulan', 'Triwulan'), ('Lampiran', 'Lampiran')], default='Tahunan', max_length=20, verbose_name='Periode'),
        ),
        migrations.AddField(
            model_name='rkapitem',
            name='subkategori',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Subkategori'),
        ),
        migrations.AddField(
            model_name='rkapitem',
            name='sumber_dokumen',
            field=models.CharField(blank=True, default='', max_length=180, verbose_name='Sumber Dokumen'),
        ),
        migrations.AddField(
            model_name='rkapitem',
            name='urutan',
            field=models.PositiveIntegerField(default=0, verbose_name='Urutan'),
        ),
    ]
