# Generated by Django 6.0.3 on 2026-06-11 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0050_alter_rkapitem_options_rkapitem_bulan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reassessmentitem',
            options={'ordering': ['summary', 'no_item', 'no_risiko'], 'verbose_name': 'Item Risiko Unit/Bidang', 'verbose_name_plural': 'TRANSAKSI UNIT - Item Risiko Bidang/Unit Bisnis'},
        ),
        migrations.AlterModelOptions(
            name='reassessmentsummary',
            options={'ordering': ['-tahun', 'judul'], 'verbose_name': 'Profil Risiko Unit/Bidang', 'verbose_name_plural': 'TRANSAKSI UNIT - Profil Risiko Bidang/Unit Bisnis'},
        ),
        migrations.AlterField(
            model_name='kpmritem',
            name='reassessment_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kpmr_item', to='risk.reassessmentitem', verbose_name='Item Risiko Bidang/Unit Bisnis'),
        ),
        migrations.AlterField(
            model_name='kpmrsummary',
            name='reassessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kpmr_summary', to='risk.reassessmentsummary', verbose_name='Profil Risiko Bidang/Unit Bisnis'),
        ),
        migrations.AlterField(
            model_name='profilrisikokorporatsumber',
            name='reassessment_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mendukung_risiko_korporat', to='risk.reassessmentitem', verbose_name='Risiko Bidang / Unit'),
        ),
        migrations.AlterField(
            model_name='reassessmentsummary',
            name='judul',
            field=models.CharField(max_length=200, verbose_name='Judul Profil Risiko'),
        ),
        migrations.AlterField(
            model_name='rkmsummary',
            name='deadline_pengajuan',
            field=models.DateField(blank=True, null=True, verbose_name='Deadline Pengajuan Profil Risiko'),
        ),
    ]
