# Generated by Django 6.0.3 on 2026-06-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0051_alter_reassessmentitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rkmitem',
            name='anggaran_rp_ribu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Anggaran (Rp Ribu)'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='hasil_analisa_program_kerja',
            field=models.TextField(blank=True, null=True, verbose_name='Hasil Analisa Program Kerja'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='inisiatif_strategis',
            field=models.TextField(blank=True, null=True, verbose_name='Inisiatif Strategis'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='jumlah_realisasi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Jumlah Realisasi'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='kategori_rkm',
            field=models.CharField(blank=True, choices=[('A', 'A - Keuangan'), ('B', 'B - Pelanggan'), ('C', 'C - Bisnis Proses Internal'), ('D', 'D - Pengembangan dan Lingkungan')], max_length=1, null=True, verbose_name='Kategori RKM'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='kpi_indikator',
            field=models.TextField(blank=True, null=True, verbose_name='KPI - Indikator'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='kpi_satuan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='KPI - Satuan'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='kpi_target',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='KPI - Target'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='mitigasi_risiko',
            field=models.TextField(blank=True, null=True, verbose_name='Mitigasi Risiko'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='persen_capaian',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='% Capaian'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='pic_rkm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PIC'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='program_kerja_utama',
            field=models.TextField(blank=True, null=True, verbose_name='Program Kerja Utama'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='realisasi_agustus',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Realisasi Agustus'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='realisasi_anggaran',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Realisasi Anggaran'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='realisasi_april',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Realisasi April'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='realisasi_desember',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Realisasi Desember'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='realisasi_februari',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Realisasi Februari'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='realisasi_januari',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Realisasi Januari'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='realisasi_juli',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Realisasi Juli'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='realisasi_juni',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Realisasi Juni'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='realisasi_maret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Realisasi Maret'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='realisasi_mei',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Realisasi Mei'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='realisasi_november',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Realisasi November'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='realisasi_oktober',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Realisasi Oktober'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='realisasi_september',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Realisasi September'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='rencana_aksi',
            field=models.TextField(blank=True, null=True, verbose_name='Rencana Aksi'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='risiko',
            field=models.TextField(blank=True, null=True, verbose_name='Risiko'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='target_akumulasi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Target Akumulasi'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='target_akumulasi_satuan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Satuan Target Akumulasi'),
        ),
    ]
