# Generated by Django 6.0.3 on 2026-06-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0054_knowledge_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsetting',
            name='ai_aktif',
            field=models.BooleanField(default=False, verbose_name='AI Aktif'),
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='ai_provider',
            field=models.CharField(choices=[('openai', 'OpenAI / ChatGPT'), ('gemini', 'Google Gemini API'), ('other', 'Provider lain')], default='openai', max_length=30, verbose_name='Provider AI'),
        ),
    ]
