# Generated by Django 6.0.3 on 2026-06-22 07:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('risk', '0055_alter_appsetting_ai_aktif_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskManagementReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul Review')),
                ('tahun', models.PositiveIntegerField(verbose_name='Tahun')),
                ('review_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Tanggal Review')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('final', 'Final')], default='draft', max_length=20)),
                ('review_summary', models.TextField(blank=True, verbose_name='Ringkasan Hasil Review Sub Bidang Manajemen Risiko')),
                ('km_notes', models.TextField(blank=True, verbose_name='Catatan Review KM')),
                ('rkm_notes', models.TextField(blank=True, verbose_name='Catatan Review RKM')),
                ('profil_risiko_notes', models.TextField(blank=True, verbose_name='Catatan Review Profil Risiko')),
                ('kpmr_notes', models.TextField(blank=True, verbose_name='Catatan Review KPMR')),
                ('recommendation', models.TextField(blank=True, verbose_name='Rekomendasi / Tindak Lanjut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diubah Pada')),
                ('kontrak_manajemen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_management_reviews', to='risk.kontrakmanajemen', verbose_name='Kontrak Manajemen')),
                ('kpmr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_management_reviews', to='risk.kpmrsummary', verbose_name='KPMR')),
                ('man_risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_reviews_as_man_risk', to=settings.AUTH_USER_MODEL, verbose_name='MAN RISK')),
                ('pairing_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_reviews_as_pairing_officer', to=settings.AUTH_USER_MODEL, verbose_name='Pairing Officer')),
                ('profil_risiko', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_management_reviews', to='risk.reassessmentsummary', verbose_name='Profil Risiko')),
                ('rkm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_management_reviews', to='risk.rkmsummary', verbose_name='RKM')),
                ('unit_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_management_reviews', to='auth.group', verbose_name='Bidang / Unit Bisnis')),
                ('vp_mrk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_reviews_as_vp_mrk', to=settings.AUTH_USER_MODEL, verbose_name='VP MRK')),
            ],
            options={
                'verbose_name': 'Review Manajemen Risiko',
                'verbose_name_plural': 'REVIEW — Manajemen Risiko',
                'ordering': ['-tahun', '-review_date', 'unit_bisnis__name'],
                'constraints': [models.UniqueConstraint(fields=('profil_risiko', 'rkm'), name='unik_review_mr_per_profil_rkm')],
            },
        ),
    ]
