# Generated by Django 6.0.3 on 2026-06-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0056_riskmanagementreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='rkmitem',
            name='target_agustus',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Target Agustus'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='target_april',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Target April'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='target_desember',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Target Desember'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='target_februari',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Target Februari'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='target_januari',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Target Januari'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='target_juli',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Target Juli'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='target_juni',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Target Juni'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='target_maret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Target Maret'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='target_mei',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Target Mei'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='target_november',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Target November'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='target_oktober',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Target Oktober'),
        ),
        migrations.AddField(
            model_name='rkmitem',
            name='target_september',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Target September'),
        ),
    ]
