# Generated by Django 6.0.3 on 2026-07-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0057_rkmitem_target_agustus_rkmitem_target_april_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='default_from_email',
            field=models.CharField(blank=True, default='', help_text='Contoh: PLNBATAM CSIRT <noreply@plnbatam.com>', max_length=255, verbose_name='Default From Email'),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='email_host',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='SMTP Host'),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='email_host_password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='SMTP Password'),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='email_host_user',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='SMTP Username'),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='email_port',
            field=models.PositiveIntegerField(default=587, verbose_name='SMTP Port'),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='email_smtp_aktif',
            field=models.BooleanField(default=False, verbose_name='SMTP Email Aktif'),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='email_use_ssl',
            field=models.BooleanField(default=False, verbose_name='SMTP Gunakan SSL'),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='email_use_tls',
            field=models.BooleanField(default=True, verbose_name='SMTP Gunakan TLS'),
        ),
    ]
