# Generated by Django 6.0.3 on 2026-07-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0058_appsetting_default_from_email_appsetting_email_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rkmitem',
            name='kategori_rkm',
            field=models.CharField(blank=True, choices=[('A', 'A - Keuangan'), ('B', 'B - Pelanggan'), ('C', 'C - Bisnis Proses Internal'), ('D', 'D - Pengembangan dan Lingkungan'), ('E', 'E - Pengembangan Talenta'), ('F', 'F - Compliance')], max_length=1, null=True, verbose_name='Kategori RKM'),
        ),
    ]
