# Generated by Django 6.0.3 on 2026-07-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0059_add_rkm_ef_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='monthly_report_notification_test_email',
            field=models.EmailField(blank=True, default='armeizir@plnbatam.com', help_text='Jika diisi, semua notifikasi laporan bulanan dikirim ke email ini, bukan ke Prepared/Reviewed/Approved by. Kosongkan saat sudah produksi.', max_length=254, verbose_name='Email Test Notifikasi Laporan Bulanan'),
        ),
    ]
