# Generated by Django 6.0.3 on 2026-07-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0068_migrate_legacy_reassessment_kpmr_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reassessmentitem',
            name='eksposur_risiko_q1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dihitung otomatis dari Nilai Dampak × Nilai Probabilitas.', max_digits=18, null=True, verbose_name='Eksposur Risiko Q1'),
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='eksposur_risiko_q2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dihitung otomatis dari Nilai Dampak × Nilai Probabilitas.', max_digits=18, null=True, verbose_name='Eksposur Risiko Q2'),
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='eksposur_risiko_q3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dihitung otomatis dari Nilai Dampak × Nilai Probabilitas.', max_digits=18, null=True, verbose_name='Eksposur Risiko Q3'),
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='eksposur_risiko_q4',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dihitung otomatis dari Nilai Dampak × Nilai Probabilitas.', max_digits=18, null=True, verbose_name='Eksposur Risiko Q4'),
        ),
    ]
