# Generated by Django 6.0.3 on 2026-07-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0069_alter_reassessmentitem_eksposur_risiko_q1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reassessmentitem',
            name='level_nilai_risiko_q1',
            field=models.CharField(blank=True, choices=[('Low', 'Rendah'), ('Low To Moderate', 'Rendah ke Moderat'), ('Moderate', 'Moderat'), ('Moderate To High', 'Moderat ke Tinggi'), ('High', 'Tinggi')], help_text='Dihitung otomatis dari Skala Risiko Q1–Q4 berdasarkan matriks heatmap.', max_length=100, null=True, verbose_name='Level Risiko Q1'),
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='level_nilai_risiko_q2',
            field=models.CharField(blank=True, choices=[('Low', 'Rendah'), ('Low To Moderate', 'Rendah ke Moderat'), ('Moderate', 'Moderat'), ('Moderate To High', 'Moderat ke Tinggi'), ('High', 'Tinggi')], help_text='Dihitung otomatis dari Skala Risiko Q1–Q4 berdasarkan matriks heatmap.', max_length=100, null=True, verbose_name='Level Risiko Q2'),
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='level_nilai_risiko_q3',
            field=models.CharField(blank=True, choices=[('Low', 'Rendah'), ('Low To Moderate', 'Rendah ke Moderat'), ('Moderate', 'Moderat'), ('Moderate To High', 'Moderat ke Tinggi'), ('High', 'Tinggi')], help_text='Dihitung otomatis dari Skala Risiko Q1–Q4 berdasarkan matriks heatmap.', max_length=100, null=True, verbose_name='Level Risiko Q3'),
        ),
        migrations.AlterField(
            model_name='reassessmentitem',
            name='level_nilai_risiko_q4',
            field=models.CharField(blank=True, choices=[('Low', 'Rendah'), ('Low To Moderate', 'Rendah ke Moderat'), ('Moderate', 'Moderat'), ('Moderate To High', 'Moderat ke Tinggi'), ('High', 'Tinggi')], help_text='Dihitung otomatis dari Skala Risiko Q1–Q4 berdasarkan matriks heatmap.', max_length=100, null=True, verbose_name='Level Risiko Q4'),
        ),
    ]
