# Generated by Django 6.0.3 on 2026-07-30 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0008_organizationunituserassignment'),
        ('risk', '0070_alter_reassessmentitem_level_nilai_risiko_q1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reassessmentitem',
            name='pic_organization_unit',
            field=models.ForeignKey(blank=True, help_text='Unit organisasi yang bertanggung jawab atas pelaksanaan perlakuan risiko.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_treatment_items', to='masterdata.organizationunit', verbose_name='PIC Organisasi'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='pic_user_assignment',
            field=models.ForeignKey(blank=True, help_text='Pengguna aktif yang ditugaskan pada PIC Organisasi.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_treatment_items', to='masterdata.organizationunituserassignment', verbose_name='PIC Pelaksana'),
        ),
    ]
