# Generated by Django 6.0.3 on 2026-08-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0071_reassessmentitem_pic_organization_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebasearticle",
            name="tutorial_placement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Tidak digunakan sebagai tutorial email"),
                    (
                        "monthly_report_email",
                        "Email Laporan Risiko Bulanan",
                    ),
                ],
                default="",
                help_text=(
                    "Pilih lokasi email tempat video tutorial ditampilkan. "
                    "Hanya satu artikel Published yang boleh aktif pada setiap lokasi."
                ),
                max_length=50,
                verbose_name="Penempatan Tutorial",
            ),
        ),
        migrations.AddField(
            model_name="knowledgebasearticle",
            name="video_youtube_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text=(
                    "Masukkan tautan YouTube, misalnya "
                    "https://www.youtube.com/watch?v=... atau https://youtu.be/..."
                ),
                max_length=500,
                verbose_name="URL Video YouTube",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgebasearticle",
            constraint=models.UniqueConstraint(
                condition=(
                    models.Q(status="published")
                    & ~models.Q(tutorial_placement="")
                ),
                fields=("tutorial_placement",),
                name="uniq_kb_published_tutorial",
            ),
        ),
    ]
