# Generated by Django 6.0.3 on 2026-08-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0073_alter_knowledgebasearticle_tutorial_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='reassessmentitem',
            name='kri_threshold_direction',
            field=models.CharField(blank=True, choices=[('higher_better', 'Semakin besar semakin baik'), ('lower_better', 'Semakin kecil semakin baik')], max_length=20, null=True, verbose_name='Arah Threshold KRI'),
        ),
    ]
