# Generated by Django 6.0.3 on 2026-08-05 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('risk', '0074_add_kri_threshold_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='reassessmentsummary',
            name='status',
            field=models.CharField(choices=[('legacy', 'Legacy / Belum diklasifikasikan'), ('draft', 'Draft'), ('approved', 'Approved'), ('final', 'Final')], default='legacy', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='ProfileCompletenessNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_to', models.JSONField(blank=True, default=list)),
                ('recipient_cc', models.JSONField(blank=True, default=list)),
                ('risk_officer_ids', models.JSONField(blank=True, default=list)),
                ('pairing_ids', models.JSONField(blank=True, default=list)),
                ('issue_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('issue_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('sent', 'Terkirim'), ('failed', 'Gagal'), ('resolved', 'Selesai')], max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completeness_notification_logs', to='risk.reassessmentsummary')),
                ('unit_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
            options={
                'verbose_name': 'Log Notifikasi Kelengkapan Profil',
                'verbose_name_plural': 'Log Notifikasi Kelengkapan Profil',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['profile', 'issue_fingerprint', 'status'], name='risk_profil_profile_d7d1a0_idx')],
            },
        ),
        migrations.AlterField(
            model_name='reassessmentsummary',
            name='status',
            field=models.CharField(choices=[('legacy', 'Legacy / Belum diklasifikasikan'), ('draft', 'Draft'), ('approved', 'Approved'), ('final', 'Final')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
