# Generated by Django 6.0.3 on 2026-08-05 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0075_profile_completeness_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='monthly_report_deadline_day',
            field=models.PositiveSmallIntegerField(default=7, help_text='Tanggal pada bulan berikutnya sebagai batas penyelesaian laporan. Gunakan angka 1 sampai 28.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='Batas Waktu Laporan Bulanan'),
        ),
    ]
