# Generated by Django 6.0.3 on 2026-08-19 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('risk', '0079_classify_existing_rkap_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCompletenessMonitor',
            fields=[
            ],
            options={
                'verbose_name': 'Monitoring Kelengkapan Profil',
                'verbose_name_plural': 'MONITORING - Kelengkapan Profil per Unit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('risk.reassessmentsummary',),
        ),
        migrations.CreateModel(
            name='ProfileCompletenessAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveIntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('required_count', models.PositiveIntegerField(default=0)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('finding_count', models.PositiveIntegerField(default=0)),
                ('issue_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completeness_assessments', to='risk.reassessmentsummary')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_completeness_assessments', to=settings.AUTH_USER_MODEL)),
                ('unit_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
            options={
                'verbose_name': 'Snapshot Kelengkapan Profil',
                'verbose_name_plural': 'Snapshot Kelengkapan Profil',
                'ordering': ('-reviewed_at',),
                'indexes': [models.Index(fields=['profile', '-reviewed_at'], name='risk_profil_profile_77932c_idx')],
            },
        ),
    ]
