# Generated by Django 6.0.3 on 2026-08-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('masterdata', '0008_organizationunituserassignment'),
        ('risk', '0080_profile_completeness_monitoring'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reassessmentitem',
            name='unik_reassessment_item_risiko_per_summary',
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='valid_from',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Berlaku Mulai'),
        ),
        migrations.AddField(
            model_name='reassessmentitem',
            name='valid_to',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Berlaku Sampai'),
        ),
        migrations.AddConstraint(
            model_name='reassessmentitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('summary', 'no_item', 'no_risiko'), name='unik_reassessment_item_aktif_per_summary'),
        ),
    ]
