# Generated by Django 6.0.3 on 2026-08-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0083_alter_reassessmentitem_eksposur_risiko_q1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemKontrakManajemenKorporat',
            fields=[
            ],
            options={
                'verbose_name': 'Item KM Korporat',
                'verbose_name_plural': 'Item KM Korporat',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('risk.itemkontrakmanajemen',),
        ),
        migrations.CreateModel(
            name='KontrakManajemenKorporat',
            fields=[
            ],
            options={
                'verbose_name': 'Kontrak Manajemen Korporat',
                'verbose_name_plural': 'Kontrak Manajemen Korporat',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('risk.kontrakmanajemen',),
        ),
        migrations.AddField(
            model_name='itemkontrakmanajemen',
            name='esg_kategori',
            field=models.CharField(blank=True, choices=[('E', 'E - Environmental'), ('S', 'S - Social'), ('G', 'G - Governance'), ('C', 'C - Corporate/Commercial')], default='', help_text='Klasifikasi ESG/C pada indikator Kontrak Manajemen.', max_length=1, verbose_name='ESG/C'),
        ),
    ]
