# Generated by Django 6.0.3 on 2026-08-30 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0084_itemkontrakmanajemenkorporat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilRisikoKorporatKinerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan Relasi')),
                ('item_kinerja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risiko_korporat_terkait', to='risk.itemkontrakmanajemen', verbose_name='IKK Korporat')),
                ('risiko_korporat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinerja_terkait', to='risk.profilrisikokorporatitem', verbose_name='Risiko Korporat')),
            ],
            options={
                'verbose_name': 'Relasi Risiko Korporat — IKK',
                'verbose_name_plural': 'KORPORAT — Relasi Risiko dan IKK',
                'ordering': ['risiko_korporat', 'item_kinerja__no_urut'],
                'constraints': [models.UniqueConstraint(fields=('risiko_korporat', 'item_kinerja'), name='unik_risiko_korporat_ikk')],
            },
        ),
    ]
