# Generated by Django 6.0.3 on 2026-09-04 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('risk', '0086_risk_treatment_change_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilRisikoKorporatRelasiUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', 'Risk Leader'), ('supporting', 'Risk Supporting')], max_length=20, verbose_name='Peran')),
                ('urutan', models.PositiveIntegerField(default=1, verbose_name='Urutan')),
                ('risiko_korporat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relasi_unit', to='risk.profilrisikokorporatitem', verbose_name='Risiko Korporat')),
                ('unit_bisnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relasi_risiko_korporat', to='auth.group', verbose_name='Bidang / Unit Bisnis')),
            ],
            options={
                'verbose_name': 'Relasi Unit Risiko Korporat',
                'verbose_name_plural': 'KORPORAT — Risk Leader & Supporting',
                'ordering': ['risiko_korporat', 'role', 'urutan', 'unit_bisnis__name'],
                'constraints': [models.UniqueConstraint(fields=('risiko_korporat', 'unit_bisnis', 'role'), name='unik_relasi_unit_risiko_korporat'), models.UniqueConstraint(condition=models.Q(('role', 'leader')), fields=('risiko_korporat',), name='unik_risk_leader_risiko_korporat')],
            },
        ),
    ]
