# Generated by Django 6.0.3 on 2026-09-18 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_risk', '0023_ai_insight_context_and_decision_draft'),
        ('risk', '0087_corporate_risk_unit_relationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_date', models.DateField(verbose_name='Decision Date')),
                ('decision_type', models.CharField(help_text='e.g., mitigation approval, risk acceptance, escalation', max_length=30, verbose_name='Decision Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executive_decisions_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('risk_metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='corporate_risk.riskmetric', verbose_name='Risk Metric')),
            ],
            options={
                'verbose_name': 'Executive Decision Log',
                'verbose_name_plural': 'Executive Decision Logs',
                'ordering': ['-decision_date'],
                'indexes': [models.Index(fields=['risk_metric', 'decision_date'], name='risk_execut_risk_me_a00331_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(verbose_name='Forecast Date')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('forecast_value', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Forecast Value')),
                ('confidence_level', models.CharField(blank=True, help_text='e.g., P5, P50, P95', max_length=10, null=True, verbose_name='Confidence Level')),
                ('scenario_type', models.CharField(blank=True, help_text='e.g., baseline, optimistic, pessimistic', max_length=20, null=True, verbose_name='Scenario Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('risk_metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_results', to='corporate_risk.riskmetric', verbose_name='Risk Metric')),
            ],
            options={
                'verbose_name': 'Risk Forecast Result',
                'verbose_name_plural': 'Risk Forecast Results',
                'ordering': ['-forecast_date', 'period_start'],
                'indexes': [models.Index(fields=['risk_metric', 'forecast_date'], name='risk_riskfo_risk_me_d75e1b_idx'), models.Index(fields=['risk_metric', 'period_start', 'period_end'], name='risk_riskfo_risk_me_4f6d5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskMetricHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Period')),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Actual Value')),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Target Value')),
                ('source', models.CharField(blank=True, help_text='e.g., manual upload, system integration', max_length=50, null=True, verbose_name='Source')),
                ('model_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Model Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('risk_metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='corporate_risk.riskmetric', verbose_name='Risk Metric')),
            ],
            options={
                'verbose_name': 'Risk Metric History',
                'verbose_name_plural': 'Risk Metric History',
                'ordering': ['-period'],
                'indexes': [models.Index(fields=['risk_metric', 'period'], name='risk_riskme_risk_me_95d324_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskScenarioResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_date', models.DateField(verbose_name='Scenario Date')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('scenario_name', models.CharField(max_length=50, verbose_name='Scenario Name')),
                ('scenario_type', models.CharField(blank=True, help_text='e.g., monte carlo, sensitivity analysis', max_length=20, null=True, verbose_name='Scenario Type')),
                ('metric_type', models.CharField(blank=True, help_text='e.g., exposure, probability, impact', max_length=20, null=True, verbose_name='Metric Type')),
                ('calculated_value', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Calculated Value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('risk_metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenario_results', to='corporate_risk.riskmetric', verbose_name='Risk Metric')),
            ],
            options={
                'verbose_name': 'Risk Scenario Result',
                'verbose_name_plural': 'Risk Scenario Results',
                'ordering': ['-scenario_date', 'scenario_name'],
                'indexes': [models.Index(fields=['risk_metric', 'scenario_date'], name='risk_risksc_risk_me_d740b5_idx'), models.Index(fields=['risk_metric', 'scenario_type', 'metric_type'], name='risk_risksc_risk_me_6f3330_idx')],
            },
        ),
    ]
