# Generated by Django 6.0.3 on 2026-05-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyriskreport',
            name='judul',
        ),
        migrations.AlterField(
            model_name='monthlyriskreport',
            name='kode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
