# Generated by Django 6.0.3 on 2026-05-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0002_remove_monthlyriskreport_judul_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyriskreport',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
