# Generated by Django 6.0.3 on 2026-05-21 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0003_monthlyriskreport_is_locked'),
        ('risk', '0046_itemkontrakmanajemen_unique_km_item_per_bagian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyriskreport',
            name='reassessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_reports', to='risk.reassessmentsummary'),
        ),
    ]
