# Generated by Django 6.0.3 on 2026-05-21 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0004_alter_monthlyriskreport_reassessment'),
        ('risk', '0046_itemkontrakmanajemen_unique_km_item_per_bagian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyriskreportitem',
            name='risk_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_report_items', to='risk.reassessmentitem', verbose_name='Item Risiko Unit/Bidang'),
        ),
    ]
