# Generated by Django 6.0.3 on 2026-05-21 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0001_initial'),
        ('masterdata', '0003_alter_periodelaporan_options'),
        ('monthly_report', '0005_alter_monthlyriskreportitem_risk_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyriskreport',
            name='kontrak_manajemen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='km.kontrakmanajemen'),
        ),
        migrations.AlterField(
            model_name='monthlyriskreport',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.unitorganisasi'),
        ),
    ]
