# Generated by Django 6.0.3 on 2026-05-21 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0006_alter_monthlyriskreport_kontrak_manajemen_and_more'),
        ('risk', '0046_itemkontrakmanajemen_unique_km_item_per_bagian'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='efektivitas_perlakuan_risiko',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Efektivitas Perlakuan Risiko'),
        ),
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='realisasi_asumsi_dampak',
            field=models.TextField(blank=True, null=True, verbose_name='Asumsi Perhitungan Dampak Realisasi'),
        ),
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='realisasi_eksposur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Eksposur Risiko Bulan Ini'),
        ),
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='realisasi_level_risiko',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Level Risiko Bulan Ini'),
        ),
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='realisasi_nilai_dampak',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Nilai Dampak Bulan Ini'),
        ),
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='realisasi_nilai_probabilitas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nilai Probabilitas Bulan Ini (%)'),
        ),
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='realisasi_skala_dampak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_report_realisasi_dampak', to='risk.masterskaladampak', verbose_name='Skala Dampak Bulan Ini'),
        ),
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='realisasi_skala_probabilitas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_report_realisasi_probabilitas', to='risk.masterskalaprobabilitas', verbose_name='Skala Probabilitas Bulan Ini'),
        ),
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='realisasi_skor_risiko',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Skala Nilai Risiko Bulan Ini'),
        ),
    ]
