# Generated by Django 6.0.3 on 2026-05-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0007_monthlyriskreportitem_efektivitas_perlakuan_risiko_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyriskreportitem',
            name='efektivitas_perlakuan_risiko',
            field=models.CharField(blank=True, choices=[('efektif', 'Efektif'), ('cukup_efektif', 'Cukup Efektif'), ('tidak_efektif', 'Tidak Efektif')], max_length=100, null=True, verbose_name='Efektivitas Perlakuan Risiko'),
        ),
    ]
