# Generated by Django 6.0.3 on 2026-05-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0008_alter_monthlyriskreportitem_efektivitas_perlakuan_risiko'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='penjelasan_status_rencana',
            field=models.TextField(blank=True, null=True, verbose_name='Penjelasan Status Rencana Perlakuan'),
        ),
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='persentase_serapan_biaya',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Persentase Serapan Biaya'),
        ),
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='progress_pelaksanaan_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Progress Pelaksanaan Bulan Ini (%)'),
        ),
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='realisasi_biaya_perlakuan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Realisasi Biaya Perlakuan Risiko'),
        ),
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='realisasi_output_perlakuan',
            field=models.TextField(blank=True, null=True, verbose_name='Realisasi Output Perlakuan Risiko'),
        ),
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='realisasi_pic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Realisasi PIC'),
        ),
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='realisasi_rencana_perlakuan',
            field=models.TextField(blank=True, null=True, verbose_name='Realisasi Rencana Perlakuan Risiko'),
        ),
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='realisasi_threshold_kri',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Realisasi Threshold KRI Bulan Ini'),
        ),
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='realisasi_threshold_kri_skor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Skor Threshold KRI Bulan Ini'),
        ),
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='status_rencana_perlakuan',
            field=models.CharField(blank=True, choices=[('continue', 'Continue'), ('discontinue', 'Discontinue')], max_length=30, null=True, verbose_name='Status Rencana Perlakuan Risiko'),
        ),
    ]
