# Generated by Django 6.0.3 on 2026-05-21 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0009_monthlyriskreportitem_penjelasan_status_rencana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRiskReportChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis_perubahan', models.CharField(choices=[('perubahan_profil', 'Perubahan profil risiko'), ('penambahan_item', 'Penambahan item risiko'), ('pengurangan_item', 'Pengurangan item risiko'), ('perubahan_strategi', 'Perubahan strategi risiko')], max_length=30, verbose_name='Jenis Perubahan')),
                ('peristiwa_risiko_terdampak', models.TextField(blank=True, null=True, verbose_name='Peristiwa Risiko yang Terdampak atas Perubahan')),
                ('penjelasan', models.TextField(blank=True, null=True, verbose_name='Penjelasan')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='monthly_report.monthlyriskreport')),
            ],
            options={
                'verbose_name': 'Ikhtisar Perubahan Profil dan Strategi Risiko',
                'verbose_name_plural': 'III.D - Ikhtisar Perubahan Profil dan Strategi Risiko',
                'db_table': 'mr_monthly_risk_report_change',
                'ordering': ['id'],
            },
        ),
    ]
