# Generated by Django 6.0.3 on 2026-05-21 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0010_monthlyriskreportchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRiskReportLossEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_kejadian', models.TextField(verbose_name='Nama Kejadian')),
                ('identifikasi_kejadian', models.TextField(blank=True, null=True, verbose_name='Identifikasi Kejadian')),
                ('kategori_kejadian', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategori Kejadian')),
                ('sumber_penyebab_kejadian', models.CharField(blank=True, choices=[('internal', 'Internal'), ('external', 'Eksternal')], max_length=20, null=True, verbose_name='Sumber Penyebab Kejadian')),
                ('penyebab_kejadian', models.TextField(blank=True, null=True, verbose_name='Penyebab Kejadian')),
                ('penanganan_saat_kejadian', models.TextField(blank=True, null=True, verbose_name='Penanganan Saat Kejadian')),
                ('deskripsi_kejadian_risk_event', models.TextField(blank=True, null=True, verbose_name='Deskripsi Kejadian - Risk Event')),
                ('kategori_risiko_bumn', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategori Risiko BUMN')),
                ('kategori_risiko_t2_t3_kbumn', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategori Risiko T2 & T3 KBUMN')),
                ('penjelasan_kerugian', models.TextField(blank=True, null=True, verbose_name='Penjelasan Kerugian')),
                ('nilai_kerugian', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Nilai Kerugian')),
                ('kejadian_berulang', models.CharField(blank=True, choices=[('ya', 'Ya'), ('tidak', 'Tidak')], max_length=10, null=True, verbose_name='Kejadian Berulang')),
                ('frekuensi_kejadian', models.CharField(blank=True, max_length=255, null=True, verbose_name='Frekuensi Kejadian')),
                ('mitigasi_direncanakan', models.TextField(blank=True, null=True, verbose_name='Mitigasi yang Direncanakan')),
                ('realisasi_mitigasi', models.TextField(blank=True, null=True, verbose_name='Realisasi Mitigasi')),
                ('perbaikan_mendatang', models.TextField(blank=True, null=True, verbose_name='Perbaikan Mendatang')),
                ('pihak_terkait', models.TextField(blank=True, null=True, verbose_name='Pihak Terkait')),
                ('status_asuransi', models.CharField(blank=True, choices=[('ya', 'Ya'), ('tidak', 'Tidak')], max_length=10, null=True, verbose_name='Status Asuransi')),
                ('nilai_premi', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Nilai Premi')),
                ('nilai_klaim', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Nilai Klaim')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loss_events', to='monthly_report.monthlyriskreport')),
            ],
            options={
                'verbose_name': 'Catatan Kejadian Kerugian',
                'verbose_name_plural': 'III.E - Catatan Kejadian Kerugian (Loss Event Database)',
                'db_table': 'mr_monthly_risk_report_loss_event',
                'ordering': ['id'],
            },
        ),
    ]
