# Generated by Django 6.0.3 on 2026-07-22 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0014_set_reviewer_from_risk_champion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyriskreport',
            name='copied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Disalin pada'),
        ),
        migrations.AddField(
            model_name='monthlyriskreport',
            name='copied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_reports_copied', to=settings.AUTH_USER_MODEL, verbose_name='Disalin oleh'),
        ),
        migrations.AddField(
            model_name='monthlyriskreport',
            name='copied_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='copied_reports', to='monthly_report.monthlyriskreport', verbose_name='Disalin dari laporan'),
        ),
        migrations.AlterField(
            model_name='monthlyriskreportsubmissionlog',
            name='action',
            field=models.CharField(choices=[('submit', 'Submit'), ('review', 'Review'), ('revise', 'Revise'), ('approve', 'Approve'), ('lock', 'Lock'), ('duplicate', 'Duplicate')], max_length=30),
        ),
    ]
