# Generated by Django 6.0.3 on 2026-07-22 22:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0015_monthlyriskreport_copied_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyriskreportsubmissionlog',
            name='action',
            field=models.CharField(choices=[('submit', 'Submit'), ('review', 'Review'), ('revise', 'Revise'), ('approve', 'Approve'), ('lock', 'Lock'), ('duplicate', 'Duplicate'), ('import', 'Import Excel')], max_length=30),
        ),
        migrations.CreateModel(
            name='MonthlyRiskReportImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file', models.FileField(upload_to='monthly_report/imports/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['xlsx'])], verbose_name='File Excel')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('analyzing', 'Sedang dianalisis'), ('review', 'Menunggu konfirmasi'), ('imported', 'Sudah diimpor'), ('failed', 'Gagal')], default='analyzing', max_length=20)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('ai_used', models.BooleanField(default=False)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_report_imports_applied', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='monthly_report.monthlyriskreport')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_report_imports_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mr_import_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyRiskReportImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_reference', models.CharField(max_length=100)),
                ('risk_code', models.CharField(blank=True, default='', max_length=100)),
                ('risk_event_text', models.TextField(blank=True, default='')),
                ('match_method', models.CharField(blank=True, default='', max_length=30)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('validation_level', models.CharField(choices=[('green', 'Siap diimpor'), ('yellow', 'Perlu konfirmasi'), ('red', 'Tidak dapat diimpor')], max_length=10)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('proposed_data', models.JSONField(blank=True, default=dict)),
                ('previous_data', models.JSONField(blank=True, default=dict)),
                ('applied_data', models.JSONField(blank=True, default=dict)),
                ('user_decision', models.CharField(choices=[('pending', 'Belum diputuskan'), ('import', 'Import'), ('skip', 'Abaikan')], default='pending', max_length=10)),
                ('user_note', models.TextField(blank=True, default='')),
                ('ai_analysis', models.TextField(blank=True, default='')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='monthly_report.monthlyriskreportimportbatch')),
                ('matched_report_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_rows', to='monthly_report.monthlyriskreportitem')),
            ],
            options={
                'db_table': 'mr_import_row',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='monthlyriskreportimportbatch',
            constraint=models.UniqueConstraint(fields=('report', 'file_sha256'), name='uniq_monthly_report_import_file'),
        ),
        migrations.AddConstraint(
            model_name='monthlyriskreportimportrow',
            constraint=models.UniqueConstraint(fields=('batch', 'source_reference'), name='uniq_monthly_report_import_row'),
        ),
    ]
