# Generated by Django 6.0.3 on 2026-07-23 02:58

import django.core.validators
import django.db.models.deletion
import monthly_report.models
import monthly_report.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0016_alter_monthlyriskreportsubmissionlog_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRiskReportEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Judul Eviden')),
                ('description', models.TextField(blank=True, default='', verbose_name='Keterangan')),
                ('file', models.FileField(max_length=500, storage=monthly_report.storage.nas_evidence_storage, upload_to=monthly_report.models.monthly_report_evidence_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'xlsx', 'xls', 'docx', 'doc', 'jpg', 'jpeg', 'png', 'zip', 'msg', 'eml']), monthly_report.models.validate_evidence_size], verbose_name='File Eviden (NAS)')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='monthly_report.monthlyriskreport', verbose_name='Laporan Risiko Bulanan')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_report_evidences_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Diunggah oleh')),
            ],
            options={
                'verbose_name': 'Eviden Laporan Risiko',
                'verbose_name_plural': 'Eviden Laporan Risiko',
                'db_table': 'mr_monthly_report_evidence',
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
