# Generated by Django 6.0.3 on 2026-07-23 03:48

import monthly_report.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0017_monthlyriskreportevidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyriskreportevidence',
            name='file',
        ),
        migrations.AddField(
            model_name='monthlyriskreportevidence',
            name='external_url',
            field=models.URLField(default='', help_text='Gunakan link file atau subfolder khusus laporan pada brightbox.plnbatam.com.', max_length=500, validators=[monthly_report.models.validate_brightbox_evidence_url], verbose_name='Link Eviden Brightbox'),
        ),
    ]
