# Generated by Django 6.0.3 on 2026-07-23 07:29

import monthly_report.models
from django.db import migrations, models


def copy_existing_evidence_link(apps, schema_editor):
    Report = apps.get_model("monthly_report", "MonthlyRiskReport")
    Evidence = apps.get_model("monthly_report", "MonthlyRiskReportEvidence")
    for report in Report.objects.filter(evidence_url="").iterator():
        evidence = Evidence.objects.filter(report_id=report.pk).order_by(
            "created_at", "pk"
        ).first()
        if evidence and evidence.external_url:
            report.evidence_url = evidence.external_url
            report.save(update_fields=["evidence_url"])


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0018_remove_monthlyriskreportevidence_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyriskreport',
            name='evidence_url',
            field=models.URLField(blank=True, default='', help_text='Tempel link folder atau file tempat eviden laporan diunggah.', max_length=500, validators=[monthly_report.models.validate_brightbox_evidence_url], verbose_name='Link Eviden Brightbox'),
        ),
        migrations.RunPython(copy_existing_evidence_link, migrations.RunPython.noop),
    ]
