# Generated by Django 6.0.3 on 2026-07-23 07:34

import monthly_report.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0019_monthlyriskreport_evidence_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyriskreport',
            name='evidence_url',
            field=models.URLField(blank=True, default='', help_text='Tempel link folder atau file tempat eviden laporan diunggah.', max_length=500, validators=[monthly_report.models.validate_https_evidence_url], verbose_name='Link Eviden'),
        ),
        migrations.AlterField(
            model_name='monthlyriskreportevidence',
            name='external_url',
            field=models.URLField(default='', help_text='Gunakan link HTTPS menuju file atau folder tempat eviden diunggah.', max_length=500, validators=[monthly_report.models.validate_https_evidence_url], verbose_name='Link Eviden'),
        ),
    ]
