# Generated by Django 6.0.3 on 2026-07-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0021_use_canonical_risk_km_relations'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='monthlyriskreportimportbatch',
            name='uniq_monthly_report_import_file',
        ),
        migrations.AddField(
            model_name='monthlyriskreportimportbatch',
            name='analysis_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='monthlyriskreportimportbatch',
            name='blocking_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='monthlyriskreportimportbatch',
            name='parser_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='monthlyriskreportimportbatch',
            name='target_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
