# Generated by Django 6.0.3 on 2026-08-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0022_remove_monthlyriskreportimportbatch_uniq_monthly_report_import_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='jenis_risiko',
            field=models.CharField(blank=True, choices=[('kuantitatif', 'Kuantitatif'), ('kualitatif', 'Kualitatif')], max_length=20, null=True, verbose_name='Jenis Risiko'),
        ),
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='realisasi_level_risiko_bumn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Level Risiko BUMN'),
        ),
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='realisasi_level_risiko_kbumn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Level Risiko KBUMN'),
        ),
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='realisasi_skala_dampak_kbumn',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Skala Dampak KBUMN'),
        ),
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='realisasi_skala_nilai_risiko_kbumn',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Skala Nilai Risiko KBUMN'),
        ),
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='realisasi_skala_probabilitas_kbumn',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Skala Probabilitas KBUMN'),
        ),
        migrations.AlterField(
            model_name='monthlyriskreportitem',
            name='efektivitas_perlakuan_risiko',
            field=models.CharField(blank=True, choices=[('efektif', 'Efektif'), ('tidak_efektif', 'Tidak Efektif')], max_length=100, null=True, verbose_name='Efektivitas Perlakuan Risiko'),
        ),
    ]
