# Generated by Django 6.0.3 on 2026-08-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0023_add_monthly_residual_kbumn_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyriskreportitem',
            name='realisasi_eksposur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True, verbose_name='Eksposur Risiko Bulan Ini'),
        ),
    ]
