# Generated by Django 6.0.3 on 2026-08-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0024_expand_manual_exposure_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='realisasi_nilai_kri',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True, verbose_name='Nilai Realisasi KRI'),
        ),
    ]
