# Generated by Django 6.0.3 on 2026-08-05 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0008_organizationunituserassignment'),
        ('monthly_report', '0025_add_kri_actual_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='realisasi_pic_organization_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_risk_report_items', to='masterdata.organizationunit', verbose_name='Realisasi PIC'),
        ),
    ]
