# Generated by Django 6.0.3 on 2026-08-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0029_sync_profile_risk_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyriskreportitem',
            name='realisasi_kri_text',
            field=models.TextField(blank=True, help_text='Digunakan bila realisasi KRI tidak dapat dinyatakan dengan satu angka, misalnya R = 101% dan I = 35%.', null=True, verbose_name='Realisasi KRI Teks/Komposit'),
        ),
    ]
