# Generated by Django 6.0.3 on 2026-08-29 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0030_add_realisasi_kri_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyriskreportimportrow',
            name='matched_report_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_rows', to='monthly_report.monthlyriskreportitem'),
        ),
    ]
