# Generated by Django 6.0.3 on 2026-09-08 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0031_allow_delete_reports_with_import_audit_rows'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRiskReportItemPairingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('sesuai', 'Sesuai'), ('perlu_perbaikan', 'Perlu Perbaikan')], max_length=30, verbose_name='Keputusan')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Komentar Pairing')),
                ('reviewed_at', models.DateTimeField(auto_now=True, verbose_name='Waktu Review')),
                ('approval_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pairing_item_reviews', to='monthly_report.monthlyriskreportsubmissionlog', verbose_name='Siklus Approval')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_reviews', to='monthly_report.monthlyriskreportitem', verbose_name='Risiko Laporan Bulanan')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_report_item_pairing_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Direview oleh')),
            ],
            options={
                'db_table': 'mr_item_pairing_review',
                'ordering': ['item__risk_event__no_item', 'item_id'],
                'constraints': [models.UniqueConstraint(fields=('item', 'approval_log'), name='uniq_pairing_review_item_approval_cycle')],
            },
        ),
    ]
