# Generated by Django 6.0.3 on 2026-08-15 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RCMControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=80, verbose_name='Referensi Kontrol')),
                ('objective', models.TextField(blank=True, verbose_name='Tujuan Kontrol')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi Kontrol')),
                ('control_type', models.CharField(blank=True, max_length=120, verbose_name='Jenis Kontrol')),
                ('is_key_control', models.BooleanField(blank=True, null=True, verbose_name='Kontrol Utama')),
                ('anti_fraud', models.BooleanField(blank=True, null=True, verbose_name='Anti Kecurangan')),
                ('supporting_application', models.CharField(blank=True, max_length=255, verbose_name='Aplikasi Pendukung')),
            ],
            options={
                'verbose_name': 'Kontrol RCM',
                'verbose_name_plural': 'ICoFR — Kontrol RCM',
                'db_table': 'icofr_rcm_control',
                'ordering': ('rcm_set', 'reference'),
            },
        ),
        migrations.CreateModel(
            name='RCMRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=80, verbose_name='Referensi Risiko')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi Risiko')),
                ('coso_objective', models.CharField(blank=True, max_length=160, verbose_name='Tujuan COSO')),
                ('coso_component', models.CharField(blank=True, max_length=160, verbose_name='Komponen COSO')),
                ('fraud_risk', models.CharField(blank=True, max_length=40, verbose_name='Risiko Kecurangan')),
                ('impact', models.CharField(blank=True, max_length=100, verbose_name='Dampak')),
                ('likelihood', models.CharField(blank=True, max_length=100, verbose_name='Kemungkinan Terjadi')),
                ('risk_level', models.CharField(blank=True, max_length=100, verbose_name='Tingkat Risiko')),
                ('coso_element', models.TextField(blank=True, verbose_name='Elemen COSO (ELC)')),
                ('control_area', models.CharField(blank=True, max_length=255, verbose_name='Area Kontrol (ITGC)')),
                ('control_sub_area', models.CharField(blank=True, max_length=255, verbose_name='Sub Area Kontrol (ITGC)')),
            ],
            options={
                'verbose_name': 'Risiko RCM',
                'verbose_name_plural': 'ICoFR — Risiko RCM',
                'db_table': 'icofr_rcm_risk',
                'ordering': ('rcm_set', 'reference'),
            },
        ),
        migrations.CreateModel(
            name='ICoFRPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(verbose_name='Tahun')),
                ('name', models.CharField(max_length=120, verbose_name='Nama Periode')),
                ('rcm_type', models.CharField(choices=[('TLC', 'Transaction Level Control (TLC)'), ('ELC', 'Entity Level Control (ELC)'), ('ITGC', 'IT General Control (ITGC)')], max_length=10, verbose_name='Jenis RCM')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Periode Awal')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Periode Akhir')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Periode ICoFR',
                'verbose_name_plural': 'ICoFR — Periode',
                'db_table': 'icofr_period',
                'ordering': ('-year', 'rcm_type', 'name'),
                'constraints': [models.UniqueConstraint(fields=('year', 'name', 'rcm_type'), name='uniq_icofr_period_year_name_type')],
            },
        ),
        migrations.CreateModel(
            name='RCMEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_name', models.CharField(blank=True, max_length=255, verbose_name='Entitas')),
                ('subprocess_number', models.CharField(blank=True, max_length=80, verbose_name='No. Sub Proses')),
                ('subprocess_description', models.TextField(blank=True, verbose_name='Deskripsi Sub Proses')),
                ('account_description', models.TextField(blank=True, verbose_name='Deskripsi Akun')),
                ('assertions_raw', models.TextField(blank=True, verbose_name='Asersi')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Lokasi')),
                ('location_description', models.TextField(blank=True, verbose_name='Deskripsi Lokasi')),
                ('frequency', models.CharField(blank=True, max_length=120, verbose_name='Frekuensi')),
                ('preparer_position', models.CharField(blank=True, max_length=255, verbose_name='Control Preparer')),
                ('reviewer_position', models.CharField(blank=True, max_length=255, verbose_name='Control Reviewer')),
                ('compensating_control', models.TextField(blank=True, verbose_name='Kontrol Kompensasi')),
                ('segment', models.CharField(blank=True, max_length=160, verbose_name='Segmen')),
                ('source_row_number', models.PositiveIntegerField(verbose_name='Baris Sumber')),
                ('source_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='icofr.rcmcontrol')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='icofr.rcmrisk')),
            ],
            options={
                'verbose_name': 'Entry RCM',
                'verbose_name_plural': 'ICoFR — Entry RCM',
                'db_table': 'icofr_rcm_entry',
                'ordering': ('rcm_set', 'source_row_number'),
            },
        ),
        migrations.CreateModel(
            name='RCMControlAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('text', models.TextField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_attributes', to='icofr.rcmentry')),
            ],
            options={
                'verbose_name': 'Atribut Kontrol',
                'verbose_name_plural': 'Atribut Kontrol',
                'db_table': 'icofr_rcm_control_attribute',
                'ordering': ('entry', 'sequence', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RCMEntryAssertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('text', models.TextField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assertions', to='icofr.rcmentry')),
            ],
            options={
                'verbose_name': 'Asersi Entry',
                'verbose_name_plural': 'Asersi Entry',
                'db_table': 'icofr_rcm_entry_assertion',
                'ordering': ('entry', 'sequence', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RCMMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Belum Dipetakan'), ('PARTIAL', 'Sebagian'), ('MAPPED', 'Terpetakan'), ('FAILED', 'Gagal Mapping'), ('MANUAL', 'Mapping Manual')], default='PENDING', max_length=20)),
                ('mapping_note', models.TextField(blank=True)),
                ('mapped_at', models.DateTimeField(blank=True, null=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapping', to='icofr.rcmentry')),
                ('mapped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icofr_mapping_actions', to=settings.AUTH_USER_MODEL)),
                ('preparer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icofr_preparer_mappings', to=settings.AUTH_USER_MODEL)),
                ('reviewer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icofr_reviewer_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mapping RCM',
                'verbose_name_plural': 'ICoFR — Mapping RCM',
                'db_table': 'icofr_rcm_mapping',
                'ordering': ('entry__rcm_set', 'entry__source_row_number'),
            },
        ),
        migrations.CreateModel(
            name='RCMSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rcm_type', models.CharField(choices=[('TLC', 'Transaction Level Control (TLC)'), ('ELC', 'Entity Level Control (ELC)'), ('ITGC', 'IT General Control (ITGC)')], max_length=10, verbose_name='Jenis RCM')),
                ('version', models.CharField(max_length=80, verbose_name='Versi')),
                ('entity_name', models.CharField(blank=True, max_length=255, verbose_name='Entitas')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Final / Locked'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('source_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source_row_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icofr_rcm_finalizations', to=settings.AUTH_USER_MODEL)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icofr_rcm_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RCM',
                'verbose_name_plural': 'ICoFR — RCM',
                'db_table': 'icofr_rcm_set',
                'ordering': ('rcm_type', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='rcmrisk',
            name='rcm_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='icofr.rcmset'),
        ),
        migrations.CreateModel(
            name='RCMImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.FileField(upload_to='icofr/import_staging/%Y/%m/', verbose_name='File RCM')),
                ('original_filename', models.CharField(max_length=255)),
                ('source_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('detected_type', models.CharField(blank=True, choices=[('TLC', 'Transaction Level Control (TLC)'), ('ELC', 'Entity Level Control (ELC)'), ('ITGC', 'IT General Control (ITGC)')], max_length=10)),
                ('detected_version', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATED', 'Validated'), ('IMPORTED', 'Imported'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icofr_import_batches', to=settings.AUTH_USER_MODEL)),
                ('imported_rcm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='icofr.rcmset')),
            ],
            options={
                'verbose_name': 'Import RCM',
                'verbose_name_plural': 'ICoFR — Riwayat Import RCM',
                'db_table': 'icofr_rcm_import_batch',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='rcmentry',
            name='rcm_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='icofr.rcmset'),
        ),
        migrations.AddField(
            model_name='rcmcontrol',
            name='rcm_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='icofr.rcmset'),
        ),
        migrations.CreateModel(
            name='RCMSupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('text', models.TextField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='icofr.rcmentry')),
            ],
            options={
                'verbose_name': 'Dokumen Pendukung',
                'verbose_name_plural': 'Dokumen Pendukung',
                'db_table': 'icofr_rcm_supporting_document',
                'ordering': ('entry', 'sequence', 'id'),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='rcmset',
            constraint=models.UniqueConstraint(fields=('rcm_type', 'version'), name='uniq_icofr_rcm_type_version'),
        ),
        migrations.AddIndex(
            model_name='rcmrisk',
            index=models.Index(fields=['rcm_set', 'reference'], name='icofr_rcm_r_rcm_set_1bb7c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='rcmrisk',
            constraint=models.UniqueConstraint(fields=('rcm_set', 'reference'), name='uniq_icofr_risk_reference_per_set'),
        ),
        migrations.AddIndex(
            model_name='rcmentry',
            index=models.Index(fields=['rcm_set', 'segment'], name='icofr_rcm_e_rcm_set_307c74_idx'),
        ),
        migrations.AddIndex(
            model_name='rcmentry',
            index=models.Index(fields=['rcm_set', 'preparer_position'], name='icofr_rcm_e_rcm_set_93afbb_idx'),
        ),
        migrations.AddIndex(
            model_name='rcmentry',
            index=models.Index(fields=['rcm_set', 'reviewer_position'], name='icofr_rcm_e_rcm_set_46b96b_idx'),
        ),
        migrations.AddConstraint(
            model_name='rcmentry',
            constraint=models.UniqueConstraint(fields=('rcm_set', 'source_row_number'), name='uniq_icofr_entry_source_row_per_set'),
        ),
        migrations.AddIndex(
            model_name='rcmcontrol',
            index=models.Index(fields=['rcm_set', 'reference'], name='icofr_rcm_c_rcm_set_37d917_idx'),
        ),
        migrations.AddConstraint(
            model_name='rcmcontrol',
            constraint=models.UniqueConstraint(fields=('rcm_set', 'reference'), name='uniq_icofr_control_reference_per_set'),
        ),
    ]
