# Generated by Django 6.0.3 on 2026-04-02 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriDampak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'md_kategori_dampak',
            },
        ),
        migrations.CreateModel(
            name='KategoriRisiko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'md_kategori_risiko',
            },
        ),
        migrations.CreateModel(
            name='KPMRParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('kelompok', models.CharField(max_length=50)),
                ('nama_parameter', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('bobot', models.DecimalField(decimal_places=2, max_digits=8)),
                ('urutan', models.PositiveIntegerField(default=1)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'md_parameter_kpmr',
                'ordering': ['urutan', 'kode'],
            },
        ),
        migrations.CreateModel(
            name='SasaranBUMN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'md_sasaran_bumn',
            },
        ),
        migrations.CreateModel(
            name='SkalaProbabilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_skala', models.PositiveSmallIntegerField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('nilai_min', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('nilai_max', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'md_skala_probabilitas',
            },
        ),
        migrations.CreateModel(
            name='TahunBuku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tahun', models.PositiveIntegerField(unique=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'md_tahun_buku',
                'ordering': ['-tahun'],
            },
        ),
        migrations.CreateModel(
            name='TaksonomiT3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'md_taksonomi_t3',
            },
        ),
        migrations.CreateModel(
            name='UnitOrganisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kode', models.CharField(max_length=30, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('jenis_unit', models.CharField(choices=[('direksi', 'Direksi'), ('direktorat', 'Direktorat'), ('bidang', 'Bidang'), ('unit', 'Unit'), ('divisi', 'Divisi'), ('subunit', 'Sub Unit')], max_length=30)),
                ('aktif', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='masterdata.unitorganisasi')),
            ],
            options={
                'db_table': 'md_unit_organisasi',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='KPMRParameterOpsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_opsi', models.CharField(max_length=10)),
                ('label_opsi', models.CharField(max_length=255)),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=8)),
                ('urutan', models.PositiveIntegerField(default=1)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opsi_list', to='masterdata.kpmrparameter')),
            ],
            options={
                'db_table': 'md_parameter_kpmr_opsi',
                'ordering': ['parameter', 'urutan'],
                'unique_together': {('parameter', 'kode_opsi')},
            },
        ),
        migrations.CreateModel(
            name='SkalaDampak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_skala', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=100)),
                ('nilai_min', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('nilai_max', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('kategori_dampak', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.kategoridampak')),
            ],
            options={
                'db_table': 'md_skala_dampak',
                'unique_together': {('kategori_dampak', 'level_skala')},
            },
        ),
        migrations.CreateModel(
            name='PeriodeLaporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kode_periode', models.CharField(max_length=20)),
                ('nama_periode', models.CharField(max_length=100)),
                ('jenis_periode', models.CharField(choices=[('tahunan', 'Tahunan'), ('triwulan', 'Triwulan'), ('bulanan', 'Bulanan')], max_length=20)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('is_locked', models.BooleanField(default=False)),
                ('tahun_buku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.tahunbuku')),
            ],
            options={
                'db_table': 'md_periode_laporan',
                'ordering': ['tahun_buku__tahun', 'tanggal_mulai'],
                'unique_together': {('tahun_buku', 'kode_periode')},
            },
        ),
    ]
