# Generated by Django 6.0.3 on 2026-04-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterBUMN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, unique=True)),
                ('kode', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'BUMN',
                'verbose_name_plural': 'MASTER — BUMN',
                'ordering': ['nama'],
            },
        ),
    ]
