# Generated by Django 6.0.3 on 2026-04-28 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_masterbumn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodelaporan',
            options={'ordering': ['-tanggal_mulai']},
        ),
    ]
