# Generated by Django 6.0.3 on 2026-05-24 00:21

import django.db.models.deletion
from django.db import migrations, models


AREAS = [
    ("0001", "DIREKSI & KOMITE"),
    ("0002", "SEKRETARIAT PERUSAHAAN"),
    ("0003", "SATUAN PENGAWASAN INTERN"),
    ("0004", "BID PERENCANAAN DAN KINERJA"),
    ("0005", "BID PENGEMBANGAN BISNIS DAN ENTERPRISE"),
    ("0006", "BID NIAGA"),
    ("0007", "UB DISTRIBUSI DAN PELAYANAN PELANGGAN"),
    ("0008", "UB INFRASTRUKTUR TEKNOLOGI INFORMASI"),
    ("0009", "BID MANAJEMEN PROYEK"),
    ("0010", "BID OPERASI"),
    ("0011", "BID K3L"),
    ("0012", "UB PEMBANGKITAN DAN TRANSMISI"),
    ("0013", "UB BRIGHT ENERGY SERVICES"),
    ("0014", "BID KEUANGAN"),
    ("0015", "BID HUMAN CAPITAL DAN GENERAL AFFAIR"),
    ("0016", "BID STRATEGI PENGADAAN"),
    ("0017", "UB MANAGED SERVICES"),
    ("0018", "BID MANAJEMEN RISIKO DAN KEPATUHAN"),
]

DIRECTORATES = [
    ("1002", "BIP"),
    ("1003", "KEUSDM"),
    ("1001", "OPS"),
]

DIVISIONS = [
    ("0011", "AGA", "1002"),
    ("0012", "BIS", "1002"),
    ("0013", "HCGA", "1003"),
    ("0010", "K3L", "1001"),
    ("0014", "KEU", "1003"),
    ("0008", "MANPRO", "1001"),
    ("0009", "OPS", "1001"),
    ("0007", "REN", "1002"),
    ("0001", "SETPER", "1002"),
    ("0006", "SPI", "1002"),
]

ROOT_ORG_UNITS = [
    ("15000000", "PT PELAYANAN LISTRIK NASIONAL BATAM", None, None, None, None),
    ("10091863", "DITBIP", "15000000", "1002", None, None),
    ("10091865", "DITKEUSDM", "15000000", "1003", None, None),
    ("10091864", "DITOPS", "15000000", "1001", None, None),
    ("10091862", "DIT UTAMA", "15000000", None, None, None),
]

DIVISION_CHILDREN = {
    "0011": [
        ("10091870", "BID AGA"),
        ("17412022", "SBID REV"),
        ("17412023", "BAG QA"),
    ],
    "0012": [
        ("10091869", "BID BIS"),
        ("17412020", "SBID PROD"),
        ("17412021", "SBID BIS"),
    ],
    "0013": [
        ("10091904", "BID HCGA"),
        ("17412115", "SBID OHC"),
        ("17412116", "BAG HC"),
        ("17412117", "SBID YANHC"),
        ("17412118", "BAG KHI"),
        ("17412119", "SBID GA"),
        ("17412120", "BAG GA"),
    ],
    "0010": [
        ("10091873", "BID K3L"),
        ("17412106", "BAG K3LYAN"),
        ("17412107", "BAG K3LKI"),
        ("17412108", "BAG K3LBES"),
    ],
    "0014": [
        ("10091903", "BID KEU"),
        ("17412109", "SBID ANG"),
        ("17412110", "SBID BEN"),
        ("17412111", "BAG BEN"),
        ("17412112", "SBID AKUN"),
        ("17412113", "BAG JAK"),
        ("17412114", "BAG KUN"),
    ],
    "0008": [
        ("10091900", "BID MANPRO"),
        ("17412057", "BAG PROP"),
        ("17412058", "BAG PROT"),
    ],
    "0009": [
        ("10091874", "BID OPS"),
        ("17412059", "SBID ASET"),
    ],
    "0007": [
        ("10091868", "BID REN"),
        ("10097560", "SBID RIS"),
        ("17412017", "SBID REN"),
        ("17412018", "BAG RES"),
        ("17412019", "SBID KIN"),
    ],
    "0001": [
        ("10091866", "SETPER"),
        ("17412007", "SBID KOM"),
        ("17412008", "BAG KOM"),
        ("17412009", "SBID SEK"),
        ("17412010", "BAG SEK"),
        ("17412011", "SBID KUM"),
        ("17412012", "BAG KUM"),
    ],
    "0006": [
        ("10091867", "SPI"),
        ("10097561", "SBID HAN"),
        ("17412013", "SBID DIT"),
        ("17412014", "BAG DIT1"),
        ("17412015", "BAG DIT2"),
    ],
}


def seed_organization(apps, schema_editor):
    CompanyCode = apps.get_model("masterdata", "CompanyCode")
    BusinessArea = apps.get_model("masterdata", "BusinessArea")
    PersonnelArea = apps.get_model("masterdata", "PersonnelArea")
    PersonnelSubArea = apps.get_model("masterdata", "PersonnelSubArea")
    Directorate = apps.get_model("masterdata", "Directorate")
    Division = apps.get_model("masterdata", "Division")
    OrganizationUnit = apps.get_model("masterdata", "OrganizationUnit")

    company, _ = CompanyCode.objects.update_or_create(
        code="1000",
        defaults={"description": "PT PLN BATAM", "aktif": True},
    )
    personnel_area, _ = PersonnelArea.objects.update_or_create(
        code="1000",
        defaults={"description": "PT PLN BATAM", "company": company, "aktif": True},
    )

    business_areas = {}
    personnel_sub_areas = {}
    for code, description in AREAS:
        business_areas[code], _ = BusinessArea.objects.update_or_create(
            company=company,
            code=code,
            defaults={"description": description, "aktif": True},
        )
        personnel_sub_areas[code], _ = PersonnelSubArea.objects.update_or_create(
            personnel_area=personnel_area,
            code=code,
            defaults={"description": description, "aktif": True},
        )

    directorates = {}
    for code, description in DIRECTORATES:
        directorates[code], _ = Directorate.objects.update_or_create(
            code=code,
            defaults={"description": description, "aktif": True},
        )

    divisions = {}
    for code, description, directorate_code in DIVISIONS:
        divisions[code], _ = Division.objects.update_or_create(
            code=code,
            defaults={
                "description": description,
                "directorate": directorates.get(directorate_code),
                "aktif": True,
            },
        )

    org_units = {}
    for code, name, parent_code, directorate_code, division_code, area_code in ROOT_ORG_UNITS:
        org_units[code], _ = OrganizationUnit.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "company": company,
                "business_area": business_areas.get(area_code),
                "personnel_area": personnel_area,
                "personnel_sub_area": personnel_sub_areas.get(area_code),
                "directorate": directorates.get(directorate_code),
                "division": divisions.get(division_code),
                "parent": org_units.get(parent_code),
                "aktif": True,
            },
        )

    directorate_parent = {
        "1002": org_units.get("10091863"),
        "1003": org_units.get("10091865"),
        "1001": org_units.get("10091864"),
    }
    division_to_area = {
        "0011": "0006",
        "0012": "0005",
        "0013": "0015",
        "0010": "0011",
        "0014": "0014",
        "0008": "0009",
        "0009": "0010",
        "0007": "0004",
        "0001": "0002",
        "0006": "0003",
    }

    for division_code, children in DIVISION_CHILDREN.items():
        division = divisions.get(division_code)
        directorate = division.directorate if division else None
        area_code = division_to_area.get(division_code)
        parent = directorate_parent.get(directorate.code) if directorate else None
        for code, name in children:
            org_units[code], _ = OrganizationUnit.objects.update_or_create(
                code=code,
                defaults={
                    "name": name,
                    "company": company,
                    "business_area": business_areas.get(area_code),
                    "personnel_area": personnel_area,
                    "personnel_sub_area": personnel_sub_areas.get(area_code),
                    "directorate": directorate,
                    "division": division,
                    "parent": parent,
                    "aktif": True,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_alter_periodelaporan_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Company Code')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company Code',
                'verbose_name_plural': 'Organization — Company Code',
                'db_table': 'md_company_code',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Directorate Code')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Directorate',
                'verbose_name_plural': 'Organization — Directorate',
                'db_table': 'md_directorate',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BusinessArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, verbose_name='Business Area')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('aktif', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_areas', to='masterdata.companycode', verbose_name='Company Code')),
            ],
            options={
                'verbose_name': 'Business Area',
                'verbose_name_plural': 'Organization — Business Area',
                'db_table': 'md_business_area',
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Division Code')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('aktif', models.BooleanField(default=True)),
                ('directorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='masterdata.directorate', verbose_name='Directorate')),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Organization — Division',
                'db_table': 'md_division',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PersonnelArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Personnel Area')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('aktif', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personnel_areas', to='masterdata.companycode', verbose_name='Company Code')),
            ],
            options={
                'verbose_name': 'Personnel Area',
                'verbose_name_plural': 'Organization — Personnel Area',
                'db_table': 'md_personnel_area',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PersonnelSubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, verbose_name='Personnel Sub Area')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('aktif', models.BooleanField(default=True)),
                ('personnel_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_areas', to='masterdata.personnelarea', verbose_name='Personnel Area')),
            ],
            options={
                'verbose_name': 'Personnel Sub Area',
                'verbose_name_plural': 'Organization — Personnel Sub Area',
                'db_table': 'md_personnel_sub_area',
                'ordering': ['code'],
                'unique_together': {('personnel_area', 'code')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Org Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('aktif', models.BooleanField(default=True)),
                ('business_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_units', to='masterdata.businessarea', verbose_name='Business Area')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_units', to='masterdata.companycode', verbose_name='Company Code')),
                ('directorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_units', to='masterdata.directorate', verbose_name='Directorate')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_units', to='masterdata.division', verbose_name='Division')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='masterdata.organizationunit', verbose_name='Parent Org Code')),
                ('personnel_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_units', to='masterdata.personnelarea', verbose_name='Personnel Area')),
                ('personnel_sub_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_units', to='masterdata.personnelsubarea', verbose_name='Personnel Sub Area')),
            ],
            options={
                'verbose_name': 'Organization Unit',
                'verbose_name_plural': 'Organization — Organization Unit',
                'db_table': 'md_organization_unit',
                'ordering': ['code'],
            },
        ),
        migrations.RunPython(seed_organization, migrations.RunPython.noop),
    ]
