# Generated by Django 6.0.3 on 2026-07-22 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('masterdata', '0004_companycode_directorate_businessarea_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationUnitAccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utama', models.BooleanField(default=True, help_text='Tandai jika unit ini merupakan cakupan utama grup.', verbose_name='Cakupan utama')),
                ('aktif', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_unit_mappings', to='auth.group', verbose_name='Bidang / Unit Bisnis')),
                ('organization_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_group_mappings', to='masterdata.organizationunit', verbose_name='Organization Unit')),
            ],
            options={
                'verbose_name': 'Cakupan Akses Organisasi',
                'verbose_name_plural': 'Organization — Cakupan Akses',
                'db_table': 'md_organization_unit_access_group',
                'ordering': ['group__name', 'organization_unit__code'],
                'constraints': [models.UniqueConstraint(fields=('organization_unit', 'group'), name='uniq_org_unit_access_group')],
            },
        ),
    ]
