# Generated by Django 6.0.3 on 2026-04-02 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KontrakManajemen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('judul', models.CharField(max_length=255)),
                ('versi', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=30)),
                ('tanggal_berlaku', models.DateField(blank=True, null=True)),
                ('tanggal_disetujui', models.DateField(blank=True, null=True)),
                ('dibuat_oleh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='km_dibuat', to=settings.AUTH_USER_MODEL)),
                ('disetujui_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='km_disetujui', to=settings.AUTH_USER_MODEL)),
                ('tahun_buku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.tahunbuku')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.unitorganisasi')),
            ],
            options={
                'db_table': 'km_kontrak_manajemen',
                'unique_together': {('tahun_buku', 'unit', 'versi')},
            },
        ),
        migrations.CreateModel(
            name='KontrakManajemenBagian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_bagian', models.CharField(max_length=30)),
                ('nama_bagian', models.CharField(max_length=255)),
                ('urutan', models.PositiveIntegerField(default=1)),
                ('kontrak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bagian_list', to='km.kontrakmanajemen')),
            ],
            options={
                'db_table': 'km_bagian',
                'ordering': ['kontrak', 'urutan'],
                'unique_together': {('kontrak', 'kode_bagian')},
            },
        ),
        migrations.CreateModel(
            name='KontrakManajemenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_urut', models.CharField(max_length=30)),
                ('indikator', models.CharField(max_length=255)),
                ('formula', models.TextField(blank=True, null=True)),
                ('satuan', models.CharField(blank=True, max_length=50, null=True)),
                ('bobot', models.DecimalField(decimal_places=2, max_digits=8)),
                ('target_tahunan', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('target_text', models.CharField(blank=True, max_length=255, null=True)),
                ('arah_pencapaian', models.CharField(choices=[('maximize', 'Maximize'), ('minimize', 'Minimize'), ('milestone', 'Milestone'), ('score', 'Score')], max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('bagian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_list', to='km.kontrakmanajemenbagian')),
                ('pic_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='km_item_pic', to='masterdata.unitorganisasi')),
            ],
            options={
                'db_table': 'km_item',
                'ordering': ['bagian', 'no_urut'],
                'unique_together': {('bagian', 'no_urut')},
            },
        ),
        migrations.CreateModel(
            name='KontrakManajemenTargetPeriode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_nilai', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('target_text', models.CharField(blank=True, max_length=255, null=True)),
                ('realisasi_nilai', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('realisasi_text', models.CharField(blank=True, max_length=255, null=True)),
                ('nilai_capaian', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('km_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_periode_list', to='km.kontrakmanajemenitem')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.periodelaporan')),
            ],
            options={
                'db_table': 'km_target_periode',
                'unique_together': {('km_item', 'periode')},
            },
        ),
    ]
