# Generated by Django 6.0.3 on 2026-04-02 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('masterdata', '0001_initial'),
        ('reassessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPMRReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('judul', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('finalized', 'Finalized'), ('approved', 'Approved')], default='draft', max_length=30)),
                ('tanggal_review', models.DateField(blank=True, null=True)),
                ('skor_total_kpmr', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('grade_kpmr', models.CharField(blank=True, max_length=10, null=True)),
                ('skor_kinerja', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('skor_komposit', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('catatan_umum', models.TextField(blank=True, null=True)),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.periodelaporan')),
                ('reassessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reassessment.reassessment')),
                ('review_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kpmr_review_lead', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kpmr_reviewed', to=settings.AUTH_USER_MODEL)),
                ('tahun_buku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.tahunbuku')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.unitorganisasi')),
            ],
            options={
                'db_table': 'kpmr_review',
                'unique_together': {('tahun_buku', 'periode', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='KPMRRiskReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hasil_review', models.CharField(max_length=50)),
                ('temuan', models.TextField(blank=True, null=True)),
                ('rekomendasi', models.TextField(blank=True, null=True)),
                ('status_tindak_lanjut', models.CharField(blank=True, max_length=30, null=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_reviews', to='kpmr.kpmrreview')),
                ('risk_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reassessment.riskevent')),
            ],
            options={
                'db_table': 'kpmr_risk_review',
            },
        ),
        migrations.CreateModel(
            name='KPMRSupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dokumen', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=50)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.attachment')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kpmr.kpmrreview')),
            ],
            options={
                'db_table': 'kpmr_supporting_document',
            },
        ),
        migrations.CreateModel(
            name='KPMRAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nilai_hasil', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('nilai_berbobot', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dokumen_referensi', models.TextField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('reviewer_note', models.TextField(blank=True, null=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.kpmrparameter')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.kpmrparameteropsi')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='kpmr.kpmrreview')),
            ],
            options={
                'db_table': 'kpmr_answer',
                'unique_together': {('review', 'parameter')},
            },
        ),
    ]
