# Generated by Django 6.0.3 on 2026-04-02 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('km', '0001_initial'),
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('judul', models.CharField(max_length=255)),
                ('versi', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revision', 'Revision'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ra_approved', to=settings.AUTH_USER_MODEL)),
                ('kontrak_manajemen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='km.kontrakmanajemen')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.periodelaporan')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ra_prepared', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ra_reviewed', to=settings.AUTH_USER_MODEL)),
                ('tahun_buku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.tahunbuku')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.unitorganisasi')),
            ],
            options={
                'db_table': 'ra_reassessment',
                'unique_together': {('tahun_buku', 'periode', 'unit', 'versi')},
            },
        ),
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no_item', models.CharField(max_length=30)),
                ('no_risiko', models.CharField(max_length=30)),
                ('peristiwa_risiko', models.TextField()),
                ('deskripsi_peristiwa', models.TextField(blank=True, null=True)),
                ('deskripsi_dampak', models.TextField(blank=True, null=True)),
                ('waktu_terpapar', models.CharField(blank=True, max_length=100, null=True)),
                ('status_risiko', models.CharField(choices=[('aktif', 'Aktif'), ('monitoring', 'Monitoring'), ('closed', 'Closed')], default='aktif', max_length=30)),
                ('prioritas', models.PositiveIntegerField(blank=True, null=True)),
                ('kategori_dampak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.kategoridampak')),
                ('kategori_risiko', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.kategoririsiko')),
                ('km_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='km.kontrakmanajemenitem')),
                ('reassessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_events', to='reassessment.reassessment')),
                ('risk_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_risks', to='masterdata.unitorganisasi')),
                ('sasaran_bumn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.sasaranbumn')),
                ('taksonomi_t3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.taksonomit3')),
            ],
            options={
                'db_table': 'ra_risk_event',
                'ordering': ['reassessment', 'no_item'],
                'unique_together': {('reassessment', 'no_risiko')},
            },
        ),
        migrations.CreateModel(
            name='RiskCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_penyebab', models.CharField(blank=True, max_length=30, null=True)),
                ('no_penyebab', models.CharField(blank=True, max_length=30, null=True)),
                ('deskripsi_penyebab', models.TextField()),
                ('urutan', models.PositiveIntegerField(default=1)),
                ('risk_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causes', to='reassessment.riskevent')),
            ],
            options={
                'db_table': 'ra_risk_cause',
                'ordering': ['risk_event', 'urutan'],
            },
        ),
        migrations.CreateModel(
            name='ExistingControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_control', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_control', models.CharField(max_length=255)),
                ('deskripsi_control', models.TextField(blank=True, null=True)),
                ('efektivitas_control', models.CharField(blank=True, max_length=30, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('pemilik_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controls_owned', to='masterdata.unitorganisasi')),
                ('risk_cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='reassessment.riskcause')),
                ('risk_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existing_controls', to='reassessment.riskevent')),
            ],
            options={
                'db_table': 'ra_existing_control',
            },
        ),
        migrations.CreateModel(
            name='RiskIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kri', models.CharField(max_length=255)),
                ('satuan', models.CharField(blank=True, max_length=50, null=True)),
                ('threshold_aman', models.CharField(blank=True, max_length=100, null=True)),
                ('threshold_hati_hati', models.CharField(blank=True, max_length=100, null=True)),
                ('threshold_bahaya', models.CharField(blank=True, max_length=100, null=True)),
                ('arah_threshold', models.CharField(blank=True, choices=[('higher_better', 'Higher Better'), ('lower_better', 'Lower Better'), ('range', 'Range')], max_length=20, null=True)),
                ('nilai_aktual', models.CharField(blank=True, max_length=100, null=True)),
                ('status_threshold', models.CharField(blank=True, max_length=30, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('risk_cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='reassessment.riskcause')),
                ('risk_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='reassessment.riskevent')),
            ],
            options={
                'db_table': 'ra_risk_indicator',
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opsi_perlakuan', models.CharField(choices=[('avoid', 'Avoid'), ('reduce', 'Reduce'), ('transfer', 'Transfer'), ('accept', 'Accept')], max_length=20)),
                ('jenis_rencana', models.CharField(blank=True, max_length=100, null=True)),
                ('rencana_perlakuan', models.TextField()),
                ('output_perlakuan', models.TextField(blank=True, null=True)),
                ('anggaran', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('ai', models.CharField(blank=True, max_length=100, null=True)),
                ('ao', models.CharField(blank=True, max_length=100, null=True)),
                ('jenis_program_rkap', models.CharField(blank=True, max_length=100, null=True)),
                ('target_mulai', models.DateField(blank=True, null=True)),
                ('target_selesai', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('on_progress', 'On Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='planned', max_length=30)),
                ('pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plan_pic', to='masterdata.unitorganisasi')),
                ('risk_cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='reassessment.riskcause')),
                ('risk_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='reassessment.riskevent')),
            ],
            options={
                'db_table': 'ra_treatment_plan',
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk_type', models.CharField(choices=[('inherent', 'Inherent'), ('residual', 'Residual'), ('target_residual', 'Target Residual')], max_length=20)),
                ('nilai_dampak', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('nilai_probabilitas', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('level_risiko', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('warna_level', models.CharField(blank=True, max_length=20, null=True)),
                ('justifikasi', models.TextField(blank=True, null=True)),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.periodelaporan')),
                ('skala_dampak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.skaladampak')),
                ('skala_probabilitas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.skalaprobabilitas')),
                ('risk_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='reassessment.riskevent')),
            ],
            options={
                'db_table': 'ra_risk_assessment',
                'unique_together': {('risk_event', 'periode', 'risk_type')},
            },
        ),
        migrations.CreateModel(
            name='TreatmentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persentase_progress', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status_realisasi', models.CharField(choices=[('not_started', 'Not Started'), ('on_progress', 'On Progress'), ('done', 'Done'), ('delayed', 'Delayed')], max_length=30)),
                ('realisasi_biaya', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eviden_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.attachment')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.periodelaporan')),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_list', to='reassessment.treatmentplan')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ra_treatment_progress',
                'unique_together': {('treatment_plan', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='TreatmentTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan_ke', models.PositiveSmallIntegerField()),
                ('planned_flag', models.BooleanField(default=False)),
                ('actual_flag', models.BooleanField(default=False)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='reassessment.treatmentplan')),
            ],
            options={
                'db_table': 'ra_treatment_timeline',
                'unique_together': {('treatment_plan', 'bulan_ke')},
            },
        ),
    ]
