# Generated by Django 6.0.3 on 2026-04-12 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0001_initial'),
        ('reassessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reassessment',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='reassessment',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='reassessment',
            name='catatan',
        ),
        migrations.RemoveField(
            model_name='reassessment',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='reassessment',
            name='approved_by_km',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ra_approved_km', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reassessment',
            name='approved_by_rkm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ra_approved_rkm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reassessment',
            name='approved_km_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reassessment',
            name='approved_rkm_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reassessment',
            name='catatan_km',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reassessment',
            name='catatan_rkm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reassessment',
            name='catatan_unit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reassessment',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reassessment',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reassessment',
            name='reviewed_by_km',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ra_reviewed_km', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reassessment',
            name='reviewed_by_rkm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ra_reviewed_rkm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reassessment',
            name='reviewed_km_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reassessment',
            name='reviewed_rkm_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='catatan_validasi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='confidence_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='escalate_to_km',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='is_key_risk',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reassessment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('review_rkm', 'Review RKM'), ('rejected_rkm', 'Rejected RKM'), ('approved_rkm', 'Approved RKM'), ('review_km', 'Review KM'), ('rejected_km', 'Rejected KM'), ('approved_km', 'Approved KM'), ('locked', 'Locked')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='riskevent',
            name='km_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_events', to='km.kontrakmanajemenitem'),
        ),
        migrations.CreateModel(
            name='ReAssessmentWorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', 'Submit'), ('review_rkm', 'Review RKM'), ('approve_rkm', 'Approve RKM'), ('reject_rkm', 'Reject RKM'), ('review_km', 'Review KM'), ('approve_km', 'Approve KM'), ('reject_km', 'Reject KM'), ('lock', 'Lock'), ('return_to_unit', 'Return To Unit')], max_length=30)),
                ('from_status', models.CharField(blank=True, max_length=30, null=True)),
                ('to_status', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ra_workflow_logs', to=settings.AUTH_USER_MODEL)),
                ('reassessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='reassessment.reassessment')),
            ],
            options={
                'db_table': 'ra_workflow_log',
                'ordering': ['-acted_at'],
            },
        ),
    ]
