# Generated by Django 6.0.3 on 2026-06-11 01:07

from django.db import migrations


PERMISSION_NAMES = {
    "existingcontrol": "Existing Control",
    "reassessment": "Profil Risiko Bidang/Unit Bisnis",
    "reassessmentworkflowlog": "Log Workflow Profil Risiko",
    "riskassessment": "Penilaian Risiko",
    "riskcause": "Penyebab Risiko",
    "riskevent": "Item Risiko Bidang/Unit Bisnis",
    "riskindicator": "Key Risk Indicator",
    "treatmentplan": "Rencana Perlakuan Risiko",
    "treatmentprogress": "Progress Perlakuan Risiko",
    "treatmenttimeline": "Timeline Perlakuan Risiko",
}

OLD_PERMISSION_NAMES = {
    "existingcontrol": "existing control",
    "reassessment": "re assessment",
    "reassessmentworkflowlog": "re assessment workflow log",
    "riskassessment": "risk assessment",
    "riskcause": "risk cause",
    "riskevent": "risk event",
    "riskindicator": "risk indicator",
    "treatmentplan": "treatment plan",
    "treatmentprogress": "treatment progress",
    "treatmenttimeline": "treatment timeline",
}


def update_permission_names(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    content_types = ContentType.objects.filter(
        app_label="reassessment",
        model__in=PERMISSION_NAMES.keys(),
    )
    for content_type in content_types:
        label = PERMISSION_NAMES[content_type.model]
        for action in ("add", "change", "delete", "view"):
            Permission.objects.filter(
                content_type=content_type,
                codename=f"{action}_{content_type.model}",
            ).update(name=f"Can {action} {label}")


def restore_permission_names(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    content_types = ContentType.objects.filter(
        app_label="reassessment",
        model__in=OLD_PERMISSION_NAMES.keys(),
    )
    for content_type in content_types:
        label = OLD_PERMISSION_NAMES[content_type.model]
        for action in ("add", "change", "delete", "view"):
            Permission.objects.filter(
                content_type=content_type,
                codename=f"{action}_{content_type.model}",
            ).update(name=f"Can {action} {label}")


class Migration(migrations.Migration):

    dependencies = [
        ('reassessment', '0002_remove_reassessment_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='existingcontrol',
            options={'verbose_name': 'Existing Control', 'verbose_name_plural': 'Existing Control'},
        ),
        migrations.AlterModelOptions(
            name='reassessment',
            options={'verbose_name': 'Profil Risiko Bidang/Unit Bisnis', 'verbose_name_plural': 'Profil Risiko Bidang/Unit Bisnis'},
        ),
        migrations.AlterModelOptions(
            name='reassessmentworkflowlog',
            options={'ordering': ['-acted_at'], 'verbose_name': 'Log Workflow Profil Risiko', 'verbose_name_plural': 'Log Workflow Profil Risiko'},
        ),
        migrations.AlterModelOptions(
            name='riskassessment',
            options={'verbose_name': 'Penilaian Risiko', 'verbose_name_plural': 'Penilaian Risiko'},
        ),
        migrations.AlterModelOptions(
            name='riskcause',
            options={'ordering': ['risk_event', 'urutan'], 'verbose_name': 'Penyebab Risiko', 'verbose_name_plural': 'Penyebab Risiko'},
        ),
        migrations.AlterModelOptions(
            name='riskevent',
            options={'ordering': ['reassessment', 'no_item'], 'verbose_name': 'Item Risiko Bidang/Unit Bisnis', 'verbose_name_plural': 'Item Risiko Bidang/Unit Bisnis'},
        ),
        migrations.AlterModelOptions(
            name='riskindicator',
            options={'verbose_name': 'Key Risk Indicator', 'verbose_name_plural': 'Key Risk Indicator'},
        ),
        migrations.AlterModelOptions(
            name='treatmentplan',
            options={'verbose_name': 'Rencana Perlakuan Risiko', 'verbose_name_plural': 'Rencana Perlakuan Risiko'},
        ),
        migrations.AlterModelOptions(
            name='treatmentprogress',
            options={'verbose_name': 'Progress Perlakuan Risiko', 'verbose_name_plural': 'Progress Perlakuan Risiko'},
        ),
        migrations.AlterModelOptions(
            name='treatmenttimeline',
            options={'verbose_name': 'Timeline Perlakuan Risiko', 'verbose_name_plural': 'Timeline Perlakuan Risiko'},
        ),
        migrations.RunPython(update_permission_names, restore_permission_names),
    ]
