# Generated by Django 6.0.3 on 2026-04-11 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0002_masterbumn'),
        ('risk', '0036_rkapitem_profilrisikokorporatitem_rkap_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonteCarloKorporatConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('direction', models.CharField(choices=[('lower', 'Semakin rendah semakin baik'), ('higher', 'Semakin tinggi semakin baik')], default='lower', max_length=10)),
                ('distribution_type', models.CharField(choices=[('normal', 'Normal'), ('triangular', 'Triangular')], default='normal', max_length=20)),
                ('n_simulations', models.PositiveIntegerField(default=1000)),
                ('minimum_history_points', models.PositiveIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('corporate_risk_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monte_carlo_config', to='risk.profilrisikokorporatitem')),
            ],
            options={
                'db_table': 'cr_mc_config',
            },
        ),
        migrations.CreateModel(
            name='MonteCarloKorporatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tanggal_data', models.DateField()),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('target_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('corporate_risk_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mc_histories', to='risk.profilrisikokorporatitem')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.periodelaporan')),
            ],
            options={
                'db_table': 'cr_mc_history',
                'ordering': ['tanggal_data'],
            },
        ),
        migrations.CreateModel(
            name='MonteCarloKorporatResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_name', models.CharField(max_length=100)),
                ('mean_value', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('p80_value', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('probability_meet_target', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('corporate_risk_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mc_results', to='risk.profilrisikokorporatitem')),
                ('forecast_periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.periodelaporan')),
            ],
            options={
                'db_table': 'cr_mc_result',
            },
        ),
    ]
