# Generated by Django 6.0.3 on 2026-04-02 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        ('reassessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateRiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('judul', models.CharField(max_length=255)),
                ('nama_perusahaan', models.CharField(default='PT PLN Batam', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('aggregated', 'Aggregated'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=30)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cr_approved', to=settings.AUTH_USER_MODEL)),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.periodelaporan')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cr_prepared', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cr_reviewed', to=settings.AUTH_USER_MODEL)),
                ('tahun_buku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.tahunbuku')),
            ],
            options={
                'db_table': 'cr_profile',
                'unique_together': {('tahun_buku', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='CorporateRiskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no_item', models.CharField(max_length=30)),
                ('sasaran_korporat', models.CharField(blank=True, max_length=255, null=True)),
                ('peristiwa_risiko', models.TextField()),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='aktif', max_length=30)),
                ('prioritas', models.PositiveIntegerField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('kategori_dampak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.kategoridampak')),
                ('kategori_risiko', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.kategoririsiko')),
                ('pemilik_risiko', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corporate_risk_owned', to='masterdata.unitorganisasi')),
                ('taksonomi_t3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.taksonomit3')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='corporate_risk.corporateriskprofile')),
            ],
            options={
                'db_table': 'cr_risk_item',
                'unique_together': {('profile', 'no_item')},
            },
        ),
        migrations.CreateModel(
            name='CorporateTreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rencana', models.TextField()),
                ('output', models.TextField(blank=True, null=True)),
                ('anggaran', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('timeline_mulai', models.DateField(blank=True, null=True)),
                ('timeline_selesai', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='planned', max_length=30)),
                ('corporate_risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='corporate_risk.corporateriskitem')),
                ('pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corporate_treatment_pic', to='masterdata.unitorganisasi')),
            ],
            options={
                'db_table': 'cr_treatment_plan',
            },
        ),
        migrations.CreateModel(
            name='CorporateRiskRealization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_dampak', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('actual_probabilitas', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('actual_level_risiko', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('realisasi_perlakuan', models.TextField(blank=True, null=True)),
                ('realisasi_biaya', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status_monitoring', models.CharField(blank=True, max_length=30, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_skala_dampak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.skaladampak')),
                ('actual_skala_probabilitas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.skalaprobabilitas')),
                ('corporate_risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizations', to='corporate_risk.corporateriskitem')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.periodelaporan')),
            ],
            options={
                'db_table': 'cr_risk_realization',
                'unique_together': {('corporate_risk', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='CorporateRiskSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bobot_kontribusi', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_primary_source', models.BooleanField(default=False)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('corporate_risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='corporate_risk.corporateriskitem')),
                ('risk_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reassessment.riskevent')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.unitorganisasi')),
            ],
            options={
                'db_table': 'cr_risk_source',
                'unique_together': {('corporate_risk', 'risk_event')},
            },
        ),
        migrations.CreateModel(
            name='CorporateRiskTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_dampak', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('target_probabilitas', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('target_level_risiko', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('corporate_risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='corporate_risk.corporateriskitem')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.periodelaporan')),
                ('target_skala_dampak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.skaladampak')),
                ('target_skala_probabilitas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.skalaprobabilitas')),
            ],
            options={
                'db_table': 'cr_risk_target',
                'unique_together': {('corporate_risk', 'periode')},
            },
        ),
    ]
