# Generated by Django 6.0.3 on 2026-04-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='montecarlokorporatresult',
            name='history_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='montecarlokorporatresult',
            name='max_value',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='montecarlokorporatresult',
            name='min_value',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='montecarlokorporatresult',
            name='p50_value',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='montecarlokorporatresult',
            name='p90_value',
            field=models.DecimalField(decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='montecarlokorporatresult',
            name='simulation_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='montecarlokorporatresult',
            name='status_hasil',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='montecarlokorporatresult',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
    ]
