# Generated by Django 6.0.3 on 2026-04-11 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_risk', '0002_montecarlokorporatresult_history_snapshot_and_more'),
        ('risk', '0036_rkapitem_profilrisikokorporatitem_rkap_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsightKorporat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executive_summary', models.TextField(blank=True, null=True)),
                ('key_drivers', models.JSONField(blank=True, default=list)),
                ('recommended_actions', models.JSONField(blank=True, default=list)),
                ('corporate_risk_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='risk.profilrisikokorporatitem')),
                ('monte_carlo_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='corporate_risk.montecarlokorporatresult')),
            ],
            options={
                'db_table': 'cr_ai_insight_korporat',
                'ordering': ['-created_at'],
            },
        ),
    ]
