# Generated by Django 6.0.3 on 2026-04-27 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_risk', '0003_aiinsightkorporat'),
        ('risk', '0036_rkapitem_profilrisikokorporatitem_rkap_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Metric')),
                ('unit', models.CharField(blank=True, default='', max_length=50, verbose_name='Satuan')),
                ('direction', models.CharField(choices=[('increase', 'Semakin besar semakin berisiko'), ('decrease', 'Semakin kecil semakin berisiko')], default='increase', max_length=20, verbose_name='Arah Risiko')),
                ('weight', models.DecimalField(decimal_places=2, default=1, help_text='Bobot untuk perhitungan composite risk score. Contoh: 0.50, 0.30, 0.20', max_digits=6, verbose_name='Bobot')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diubah pada')),
                ('corporate_risk_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_metrics', to='risk.profilrisikokorporatitem', verbose_name='Item Risiko Korporat')),
            ],
            options={
                'verbose_name': 'Risk Metric',
                'verbose_name_plural': 'Risk Metrics',
                'ordering': ('corporate_risk_item', 'name'),
                'unique_together': {('corporate_risk_item', 'name')},
            },
        ),
    ]
