# Generated by Django 6.0.3 on 2026-04-27 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_risk', '0004_riskmetric'),
        ('masterdata', '0002_masterbumn'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonteCarloMetricHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_data', models.DateField(verbose_name='Tanggal Data')),
                ('metric_value', models.DecimalField(decimal_places=4, max_digits=24, verbose_name='Nilai Aktual')),
                ('target_value', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True, verbose_name='Target')),
                ('keterangan', models.TextField(blank=True, default='', verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diubah pada')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_histories', to='corporate_risk.riskmetric', verbose_name='Risk Metric')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.periodelaporan', verbose_name='Periode')),
            ],
            options={
                'verbose_name': 'Monte Carlo Metric History',
                'verbose_name_plural': 'Monte Carlo Metric Histories',
                'ordering': ('metric', 'tanggal_data'),
                'unique_together': {('metric', 'periode')},
            },
        ),
    ]
