# Generated by Django 6.0.3 on 2026-04-28 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_risk', '0005_montecarlometrichistory'),
        ('masterdata', '0002_masterbumn'),
        ('risk', '0036_rkapitem_profilrisikokorporatitem_rkap_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiMetricMonteCarloResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composite_score', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Composite Risk Score')),
                ('p80_score', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='P80 Composite Score')),
                ('status_hasil', models.CharField(blank=True, default='', max_length=100, verbose_name='Status Hasil')),
                ('metric_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot Metric')),
                ('simulation_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot Simulasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diubah pada')),
                ('corporate_risk_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_metric_results', to='risk.profilrisikokorporatitem', verbose_name='Item Risiko Korporat')),
                ('forecast_periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.periodelaporan', verbose_name='Periode Forecast')),
            ],
            options={
                'verbose_name': 'Multi Metric Monte Carlo Result',
                'verbose_name_plural': 'Multi Metric Monte Carlo Results',
                'ordering': ('-created_at',),
                'unique_together': {('corporate_risk_item', 'forecast_periode')},
            },
        ),
    ]
