# Generated by Django 6.0.3 on 2026-04-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_risk', '0006_multimetricmontecarloresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskmetric',
            name='threshold',
            field=models.FloatField(default=1, help_text='Nilai batas risiko (untuk normalisasi ke 0–100)', verbose_name='Threshold Risiko'),
        ),
    ]
