# Generated by Django 6.0.3 on 2026-04-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_risk', '0007_riskmetric_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimetricmontecarloresult',
            name='scenario_percentile',
            field=models.PositiveSmallIntegerField(choices=[(40, 'P40 - Moderat'), (50, 'P50 - Median'), (60, 'P60 - Konservatif ringan'), (80, 'P80 - Konservatif'), (90, 'P90 - Stress scenario')], default=80, verbose_name='Scenario Percentile'),
        ),
    ]
