# Generated by Django 6.0.3 on 2026-04-29 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_risk', '0008_multimetricmontecarloresult_scenario_percentile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiMetricAIInsightKorporat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_summary', models.TextField()),
                ('key_findings', models.TextField()),
                ('recommended_actions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('multi_metric_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insight_multi_metric', to='corporate_risk.multimetricmontecarloresult')),
            ],
            options={
                'verbose_name': 'AI Insight Multi Metric Korporat',
                'verbose_name_plural': 'AI Insight Multi Metric Korporat',
            },
        ),
    ]
