# Generated by Django 6.0.3 on 2026-05-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_risk', '0009_multimetricaiinsightkorporat'),
    ]

    operations = [
        migrations.AddField(
            model_name='montecarlokorporatresult',
            name='average_selling_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='montecarlokorporatresult',
            name='baseline_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='montecarlokorporatresult',
            name='best_case_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='montecarlokorporatresult',
            name='forecast_total',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='montecarlokorporatresult',
            name='potential_loss',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='montecarlokorporatresult',
            name='probability_achieve_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='montecarlokorporatresult',
            name='probability_not_achieve_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='montecarlokorporatresult',
            name='requires_mitigation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='montecarlokorporatresult',
            name='risk_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='montecarlokorporatresult',
            name='target_gap',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='montecarlokorporatresult',
            name='target_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='montecarlokorporatresult',
            name='var_95',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='montecarlokorporatresult',
            name='worst_case_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='multimetricmontecarloresult',
            name='average_selling_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='multimetricmontecarloresult',
            name='baseline_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='multimetricmontecarloresult',
            name='best_case_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='multimetricmontecarloresult',
            name='forecast_total',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='multimetricmontecarloresult',
            name='potential_loss',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='multimetricmontecarloresult',
            name='probability_achieve_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='multimetricmontecarloresult',
            name='probability_not_achieve_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='multimetricmontecarloresult',
            name='requires_mitigation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multimetricmontecarloresult',
            name='risk_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='multimetricmontecarloresult',
            name='target_gap',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='multimetricmontecarloresult',
            name='target_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='multimetricmontecarloresult',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='multimetricmontecarloresult',
            name='var_95',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='multimetricmontecarloresult',
            name='worst_case_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='average_selling_price',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Digunakan untuk menghitung potential loss = gap x harga jual rata-rata.', max_digits=24, verbose_name='Harga Jual Rata-rata'),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='is_target_metric',
            field=models.BooleanField(default=False, help_text='Aktifkan untuk metric demand/penjualan yang dihitung terhadap target RKAP.', verbose_name='Metric Target Utama'),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='risk_appetite_threshold',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=6, verbose_name='Risk Appetite Probabilitas Tidak Tercapai (%)'),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='risk_appetite_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True, verbose_name='Risk Appetite Nilai Kerugian'),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Target total sampai akhir tahun. Jika kosong, sistem memakai target dari histori terakhir.', max_digits=24, null=True, verbose_name='Target RKAP'),
        ),
    ]
