# Generated by Django 6.0.3 on 2026-05-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_risk', '0010_montecarlokorporatresult_average_selling_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimetricmontecarloresult',
            name='forecast_periods',
            field=models.PositiveSmallIntegerField(default=9, help_text='Jumlah periode/bulan ke depan yang diproyeksikan.', verbose_name='Periods to Forecast'),
        ),
        migrations.AddField(
            model_name='multimetricmontecarloresult',
            name='forecasting_method',
            field=models.CharField(choices=[('best_fit_normal_growth', 'Best Fit - Normal Growth Monte Carlo'), ('double_exponential_smoothing', 'Double Exponential Smoothing'), ('moving_average', 'Moving Average'), ('linear_trend', 'Linear Trend')], default='best_fit_normal_growth', max_length=40, verbose_name='Pilihan Forecasting / Prediksi Time Series'),
        ),
        migrations.AddField(
            model_name='multimetricmontecarloresult',
            name='n_simulations',
            field=models.PositiveIntegerField(default=10000, help_text='Standar Crystal Ball biasanya 10,000 trials.', verbose_name='Monte Carlo Trials'),
        ),
        migrations.AddField(
            model_name='multimetricmontecarloresult',
            name='prediction_interval',
            field=models.CharField(choices=[('5_95', '5% dan 95%'), ('10_90', '10% dan 90%'), ('20_80', '20% dan 80%')], default='5_95', max_length=10, verbose_name='Prediction Interval'),
        ),
    ]
