# Generated by Django 6.0.3 on 2026-05-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_risk', '0011_multimetricmontecarloresult_forecast_periods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montecarlokorporatconfig',
            name='n_simulations',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
