# Generated by Django 6.0.3 on 2026-05-26 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_risk', '0012_alter_montecarlokorporatconfig_n_simulations'),
        ('risk', '0049_appsetting_system_integrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskmetric',
            name='rkap_item',
            field=models.ForeignKey(blank=True, help_text='Pilih item RKAP agar target otomatis diambil dari tabel RKAP.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_metrics', to='risk.rkapitem', verbose_name='Sumber Target RKAP'),
        ),
        migrations.AlterField(
            model_name='riskmetric',
            name='is_target_metric',
            field=models.BooleanField(default=False, help_text='Aktifkan untuk metric utama yang dihitung terhadap target RKAP.', verbose_name='Metric Target Utama'),
        ),
        migrations.AlterField(
            model_name='riskmetric',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Opsional. Jika kosong, sistem memakai target dari Sumber Target RKAP, lalu target histori terakhir.', max_digits=24, null=True, verbose_name='Target RKAP Override'),
        ),
    ]
