# Generated by Django 6.0.3 on 2026-06-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_risk', '0015_multimetricmontecarloresult_distribution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimetricmontecarloresult',
            name='dampak_base_case',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='multimetricmontecarloresult',
            name='dampak_best_case',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='multimetricmontecarloresult',
            name='dampak_worst_case',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True),
        ),
    ]
