# Generated by Django 6.0.3 on 2026-06-18 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_risk', '0017_multimetric_distribution_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimetricmontecarloresult',
            name='n_simulations',
            field=models.PositiveIntegerField(default=10000, help_text='Minimal 1,000 trials. Rekomendasi 10,000 trials untuk hasil yang lebih stabil.', validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Monte Carlo Trials'),
        ),
    ]
