# Generated by Django 6.0.3 on 2026-07-23 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_risk', '0018_alter_multimetricmontecarloresult_n_simulations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='montecarlometrichistory',
            name='copied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Disalin pada'),
        ),
        migrations.AddField(
            model_name='montecarlometrichistory',
            name='copied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metric_histories_copied', to=settings.AUTH_USER_MODEL, verbose_name='Disalin oleh'),
        ),
        migrations.AddField(
            model_name='montecarlometrichistory',
            name='copied_from',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='copied_history', to='corporate_risk.montecarlometrichistory', verbose_name='Sumber Salinan'),
        ),
        migrations.AddField(
            model_name='montecarlometrichistory',
            name='status',
            field=models.CharField(choices=[('unupdated', 'Belum diperbarui'), ('updated', 'Sudah diperbarui'), ('verified', 'Terverifikasi')], default='updated', max_length=20, verbose_name='Status Data'),
        ),
    ]
