# Generated by Django 6.0.3 on 2026-07-23 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_risk', '0019_montecarlometrichistory_copied_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='montecarlometrichistory',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_metric_histories', to=settings.AUTH_USER_MODEL, verbose_name='User Pengisi Data'),
        ),
        migrations.AddField(
            model_name='montecarlometrichistory',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Diisi pada'),
        ),
        migrations.AddField(
            model_name='montecarlometrichistory',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_metric_histories', to=settings.AUTH_USER_MODEL, verbose_name='Diisi oleh'),
        ),
        migrations.AddField(
            model_name='montecarlometrichistory',
            name='notification_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Jumlah Notifikasi'),
        ),
        migrations.AddField(
            model_name='montecarlometrichistory',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Notifikasi Terakhir'),
        ),
    ]
